### ISSUE TITLE
NPE in GitMacheteRepositoryUpdateBackgroundable.java:91 during UI tests

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1000]
## Problem

This is **very** unexpected, given how tight the nullness checks are.

It looks that the result of `com.virtuslab.gitmachete.backend.api.IGitMacheteRepositoryCache#getInstance` is null... which is possible, looking at the implementation of `com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryCache#getInstance`.

It might've happened that right before `return gitMacheteRepositoryCache.get(key);`, the entry for `key` has been GCed out of the map. Pls verify if this scenario was indeed possible given `WeakHashMap`'s contract... but I can't see why it wouldn't be.

## Remedy

My quick idea to prevent **all bugs like that forever** (and not just fix this particular place) is the following:
1. change the compile-time type of `com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryCache#gitMacheteRepositoryCache` from `java.util.Map` to `java.util.WeakHashMap`
2. ban, via ArchUnit, all calls to `java.util.WeakHashMap#containsKey` (optional, to be reconsidered)
3. mark the result `java.util.WeakHashMap#get` as `@Nullable` via Checker stubs (or maybe even more aggresively... `java.util.Map#get` as `@Nullable`? TBD... then point 1. isn't even needed)
4. and now simply follow the errors from Checker and ArchUnit (i.e. remove `containsKey` call, instead call `get` but check the result for nullness)

# Logs

https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/5672/workflows/a66df1df-04ff-4eb5-a423-a8bbfe890147/jobs/5989/steps:

```
com.virtuslab.gitmachete.uitest.UITestSuite > skipNonExistentBranches_toggleListingCommits_slideOutRoot STANDARD_OUT
    IntelliJ build number is 2021.2.4
    request[projects/all]: ()
    response: []
    request[project/open]: "/tmp/machete-tests-5762239941126079569/machete-sandbox-worktree"
    response: ()
    Waiting for 2 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0, ProgressIndicatorEx 1670403980: running=false; canceled=true; reusable=true]
    [intellij-stderr] 2022-07-19 17:20:06,914 [ 258678]   WARN - ernallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree 
    runJs: executing `project.configure()`
    runJs: executed `project.configure()`
    request[projects/all]: ()
    response: [{"name":"machete-sandbox-worktree"}]
    runJs: executing `project.openGitMacheteTab()`
    runJs: executed `project.openGitMacheteTab()`
    callJs: evaluating `project.refreshGraphTableModel(); project.getManagedBranches()`
    [intellij-stderr] 2022-07-19 17:20:15,929 [ 267693]   WARN - RepositoryUpdateBackgroundable - Unable to create Git Machete repository 
    [intellij-stderr] java.lang.NullPointerException
    [intellij-stderr] 	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.lambda$updateRepositorySnapshot$47bf2c18$1(GitMacheteRepositoryUpdateBackgroundable.java:91)
    [intellij-stderr] 	at io.vavr.control.Try.of(Try.java:75)
    [intellij-stderr] 	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.updateRepositorySnapshot(GitMacheteRepositoryUpdateBackgroundable.java:88)
    [intellij-stderr] 	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.run(GitMacheteRepositoryUpdateBackgroundable.java:63)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
    [intellij-stderr] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    [intellij-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    [intellij-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    [intellij-stderr] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    [intellij-stderr] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    [intellij-stderr] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
    [intellij-stderr] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    [intellij-stderr] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by PawelLipski** [comment]
Okay... I've done a quick check, looks that adding `@Nullable` on return type of `java.util.Map#get` and `java.util.WeakHashMap#get` doesn't change anything :/// [Map Key Checker](https://checkerframework.org/manual/#map-key-checker), executed under the hood by Nullness checker, probably treats these methods specially.

So I'm not sure if anything can be done currently to prevent the errors on `WeakHashMap` in general case. We can just:
1. fix the individual case of `com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryCache#getInstance` by doing sth like
```java
var value = map.get(key);
if (value == null) {
 ....
 map.put(key, computedValue);
 return computedValue;
} else {
  return value;
}
```
2. open an issue against Checker Framework that would highlight the case of WeakHashMap... the repro should be easy, just call `System.gc()` b/w `containsKey` and `get`. See https://www.baeldung.com/java-weakhashmap#weakhashmap-as-an-efficient-memory-cache
