### ISSUE TITLE
`org.eclipse.jgit.errors.MissingObjectException: Missing unknown <commit hash>`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1029]
As reported by @mkondratek:

```
Unable to create Git Machete repository

com.virtuslab.gitmachete.backend.api.GitMacheteException: com.virtuslab.gitcore.api.GitCoreException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 0958ae8b40cfcdd991af5fa08709011c43344f51
	at com.virtuslab.gitmachete.backend.api.GitMacheteException.getOrWrap(GitMacheteException.java:21)
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createSnapshot(GitMacheteRepository.java:312)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout_aroundBody0(GitMacheteRepository.java:83)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$AjcClosure1.run(GitMacheteRepository.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:211)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:167)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout(GitMacheteRepository.java:82)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.lambda$updateRepositorySnapshot$47bf2c18$1(GitMacheteRepositoryUpdateBackgroundable.java:91)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.updateRepositorySnapshot(GitMacheteRepositoryUpdateBackgroundable.java:88)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.run(GitMacheteRepositoryUpdateBackgroundable.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.virtuslab.gitcore.api.GitCoreException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 0958ae8b40cfcdd991af5fa08709011c43344f51
	at com.virtuslab.gitcore.api.GitCoreException.getOrWrap(GitCoreException.java:21)
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.deriveChildBranches(GitMacheteRepository.java:632)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createGitMacheteRootBranch(GitMacheteRepository.java:402)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$createSnapshot$4cd04c2b$1(GitMacheteRepository.java:311)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$createSnapshot$0(GitMacheteRepository.java:311)
	at io.vavr.collection.List.map(List.java:1042)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createSnapshot(GitMacheteRepository.java:311)
	... 31 more
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 0958ae8b40cfcdd991af5fa08709011c43344f51
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:214)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1086)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:996)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$convertRevisionToGitCoreCommit$be3c0398$1(GitCoreRepository.java:150)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.withRevWalkUnchecked(GitCoreRepository.java:132)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$convertRevisionToGitCoreCommit$3(GitCoreRepository.java:150)
	at io.vavr.control.Option.map(Option.java:392)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.convertRevisionToGitCoreCommit(GitCoreRepository.java:150)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.parseRevision(GitCoreRepository.java:117)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.deriveParentAgnosticOverriddenForkPoint(GitMacheteRepository.java:558)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.deriveParentAwareForkPoint(GitMacheteRepository.java:487)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createGitMacheteNonRootBranch(GitMacheteRepository.java:438)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$deriveChildBranches$9269a38a$1(GitMacheteRepository.java:630)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$deriveChildBranches$24(GitMacheteRepository.java:629)
	at io.vavr.collection.List.map(List.java:1042)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.deriveChildBranches(GitMacheteRepository.java:629)
	... 37 more
```

**Comment by PawelLipski** [comment]
Rel: https://github.com/VirtusLab/git-machete/issues/609

**Comment by PawelLipski** [comment]
Oh! a commit recorded as `whileDescendentOf` in fork point override no longer exists:

```
machete.overrideForkPoint.chore/drop-support-for-2021.1.whiledescendantof=0958ae8b40cfcdd991af5fa08709011c43344f51
```

This is surprising, I thought there's a proper validation for these values... anyway, for a workaround @mkondratek, just run
```
git machete fork-point --unset-override chore/drop-support-for-2021.1
```

**Comment by mkondratek** [comment]
thank you!

**Comment by PawelLipski** [comment]
Rel: #1008, coz it was the triple-wrapping of the exceptions here that led to a too long GitHub URL ;p
