### ISSUE TITLE
`syncToParentByRebaseAction` UI test failing: NPE when checking out a branch, followed by `SocketTimeoutException`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1043]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/5913/workflows/e833be69-ed25-448d-8d84-a4d581fb81f4/jobs/6241

TBH, this looks to me like a spurious error in IDEA itself. Probably the only fix could be to retry checkout.
Maybe it'll even never reoccur once we drop support for 2021.3.

```
com.virtuslab.gitmachete.uitest.UITestSuite > syncToParentByRebaseAction STANDARD_OUT
    [intellij-stdout] closed javax.swing.Popup$HeavyWeightWindow
    IntelliJ build number is 2021.3.3
    request[projects/all]: ()
    response: []
    [intellij-stdout] closed com.intellij.openapi.wm.impl.IdeFrameImpl
    [intellij-stdout] opened com.intellij.openapi.wm.impl.IdeFrameImpl
    request[project/open]: "/tmp/machete-tests-4260935497926976343/machete-sandbox-worktree"
    response: ()
    Waiting for 1 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0]
    [intellij-stderr] 2022-08-08 19:57:39,095 [ 131801]   WARN - ernallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree 
    [intellij-stdout] opened javax.swing.JWindow
    runJs: executing `project.configure()`
    runJs: executed `project.configure()`
    request[projects/all]: ()
    response: [{"name":"machete-sandbox-worktree"}]
    runJs: executing `project.openGitMacheteTab()`
    runJs: executed `project.openGitMacheteTab()`
    runJs: executing `project.checkoutBranch('allow-ownership-link')`
    runJs: executed `project.checkoutBranch('allow-ownership-link')`
    Waiting for 2 background task(s)... [Checking out 1181322119: running=true; canceled=false; task=com.virtuslab.gitmachete.frontend.actions.contextmenu.CheckoutSelectedBranchAction$1@782deeab, Updating Git Machete status 1448653827: running=true; canceled=false; task=com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable@730b97bc]
    [intellij-stdout] closed javax.swing.JWindow
    [intellij-stderr] 2022-08-08 19:57:48,356 [ 141062]  ERROR - intellij.openapi.progress.Task - null 
    [intellij-stderr] java.lang.NullPointerException
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverImmediately(MessageBusConnectionImpl.java:61)
    [intellij-stderr] 	at com.intellij.psi.impl.file.impl.FileManagerImpl.dispatchPendingEvents(FileManagerImpl.java:311)
    [intellij-stderr] 	at com.intellij.psi.impl.file.impl.FileManagerImpl.getCachedPsiFile(FileManagerImpl.java:378)
    [intellij-stderr] 	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:143)
    [intellij-stderr] 	at com.intellij.psi.impl.PsiDocumentManagerImpl$1.lambda$fileContentLoaded$0(PsiDocumentManagerImpl.java:55)
    [intellij-stderr] 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
    [intellij-stderr] 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
    [intellij-stderr] 	at com.intellij.psi.impl.PsiDocumentManagerImpl$1.fileContentLoaded(PsiDocumentManagerImpl.java:55)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
    [intellij-stderr] 	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
    [intellij-stderr] 	at com.sun.proxy.$Proxy177.batchChangeStarted(Unknown Source)
    [intellij-stderr] 	at com.intellij.dvcs.DvcsUtil.workingTreeChangeStarted(DvcsUtil.java:152)
    [intellij-stderr] 	at git4idea.branch.GitCheckoutOperation.doExecute(GitCheckoutOperation.java:115)
    [intellij-stderr] 	at git4idea.branch.GitCheckoutOperation.execute(GitCheckoutOperation.java:95)
    [intellij-stderr] 	at git4idea.branch.GitBranchWorker.checkout(GitBranchWorker.java:116)
    [intellij-stderr] 	at com.virtuslab.gitmachete.frontend.actions.contextmenu.CheckoutSelectedBranchAction.doCheckout(CheckoutSelectedBranchAction.java:102)
    [intellij-stderr] 	at com.virtuslab.gitmachete.frontend.actions.contextmenu.CheckoutSelectedBranchAction$1.run(CheckoutSelectedBranchAction.java:89)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    [intellij-stderr] 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
    [intellij-stderr] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    [intellij-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    [intellij-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    [intellij-stderr] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    [intellij-stderr] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    [intellij-stderr] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
    [intellij-stderr] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    [intellij-stderr] 	at java.base/java.lang.Thread.run(Thread.java:829)
    [intellij-stderr] 2022-08-08 19:57:48,360 [ 141066]  ERROR - intellij.openapi.progress.Task - IntelliJ IDEA 2021.3.3  Build #IC-213.7172.25 
    [intellij-stderr] 2022-08-08 19:57:48,360 [ 141066]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
    [intellij-stderr] 2022-08-08 19:57:48,361 [ 141067]  ERROR - intellij.openapi.progress.Task - OS: Linux 
    [intellij-stderr] 2022-08-08 19:57:48,361 [ 141067]  ERROR - intellij.openapi.progress.Task - Last Action: GitMachete.SyncSelectedToParentByMergeAction 
    runJs: executing `project.toolbar.syncByRebase()`
    runJs: executing `ide.closeOpenedProjects()`

com.virtuslab.gitmachete.uitest.UITestSuite > syncToParentByRebaseAction FAILED
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:59)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:35)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.com$virtuslab$gitmachete$uitest$RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$$runJs(RunningIntelliJFixtureExtension.scala:47)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$project$toolbar$.syncByRebase(RunningIntelliJFixtureExtension.scala:223)
        at com.virtuslab.gitmachete.uitest.UITestSuite.syncToParentByRebaseAction(UITestSuite.scala:160)

        Caused by:
        java.net.SocketException: Socket closed
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at okio.Okio$2.read(Okio.java:140)
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
            ... 27 more

```

**Comment by PawelLipski** [comment]
Never seen since we've gone back to invoking actions explicitly (instead of clicking on buttons)... closing
