### ISSUE TITLE
`squashBranch` UI test failing: `java.net.SocketTimeoutException: timeout` on `project.toolbar.toggleListingCommits()`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1069]
E.g. https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6083/workflows/0d871a65-4783-4361-bfc1-50e23f6d9a2c/jobs/6424

Happens quite often, always in the same place:

```
com.virtuslab.gitmachete.uitest.UITestSuite > squashBranch STANDARD_OUT
    IntelliJ build number is 2021.1.3
    request[projects/all]: ()
    response: []
    request[project/open]: "/tmp/machete-tests-6509912699089884645/machete-sandbox-worktree"
    [intellij-stdout] opened com.intellij.openapi.wm.impl.IdeFrameImpl
    [intellij-stdout] closed Welcome to IntelliJ IDEA (ROOT)
    response: ()
    Waiting for 1 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0]
    Waiting for 1 background task(s)... [Updating indexes 1079045034: running=true; canceled=false; task=com.intellij.openapi.project.DumbServiceImpl$5@4f6fdce8]
    runJs: executing `project.configure()`
    runJs: executed `project.configure()`
    request[projects/all]: ()
    response: [{"name":"machete-sandbox-worktree"}]
    Waiting for 1 background task(s)... [com.intellij.openapi.progress.EmptyProgressIndicator@c89c21]
    runJs: executing `project.openGitMacheteTab()`
    runJs: executed `project.openGitMacheteTab()`
    runJs: executing `project.toolbar.toggleListingCommits()`
    runJs: executing `ide.closeOpenedProjects()`
    request[screenshot]: "exception"
    response: ()

com.virtuslab.gitmachete.uitest.UITestSuite > squashBranch FAILED
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:59)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:35)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.com$virtuslab$gitmachete$uitest$RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$$runJs(RunningIntelliJFixtureExtension.scala:47)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$project$toolbar$.$anonfun$toggleListingCommits$1(RunningIntelliJFixtureExtension.scala:255)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.doAndAwait(RunningIntelliJFixtureExtension.scala:38)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$project$toolbar$.toggleListingCommits(RunningIntelliJFixtureExtension.scala:255)
        at com.virtuslab.gitmachete.uitest.UITestSuite.squashBranch(UITestSuite.scala:224)

        Caused by:
        java.net.SocketException: Socket closed
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at okio.Okio$2.read(Okio.java:140)
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
            ... 29 more

    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:59)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:35)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.com$virtuslab$gitmachete$uitest$RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$$runJs(RunningIntelliJFixtureExtension.scala:47)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$ide$.closeOpenedProjects(RunningIntelliJFixtureExtension.scala:74)
        at com.virtuslab.gitmachete.uitest.UISuite.waitAndCloseProject(UISuite.scala:28)
        at com.virtuslab.gitmachete.uitest.UISuite.waitAndCloseProject$(UISuite.scala:24)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.waitAndCloseProject(UITestSuite.scala:18)
        at com.virtuslab.gitmachete.uitest.UITestSuite.afterEach(UITestSuite.scala:39)

        Caused by:
        java.net.SocketException: Socket closed
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at okio.Okio$2.read(Okio.java:140)
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
            ... 30 more
```

**Comment by PawelLipski** [comment]
This one is likely to have been fixed with #1081. Let's close and reopen if needed.
