### ISSUE TITLE
`squashBranch` UI test failing: `expected:<15> but was:<16>`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1079]
This is rare, so far only seen in:

https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6116/workflows/50e67100-2a7f-445d-bb56-406b24cbf9e3/jobs/6459/steps:

```
com.virtuslab.gitmachete.uitest.UITestSuite > squashBranch STANDARD_OUT
    [intellij-stdout] closed com.intellij.ui.Splash
    IntelliJ build number is 2021.3.3
    request[projects/all]: ()
    response: []
    [intellij-stdout] 2022-08-22 10:29:17,891 [   8388]   WARN - ctionSystem.impl.ActionUpdater - 215 ms to grab EDT for LargeIconWithTextWrapper#update (com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil$LargeIconWithTextWrapper) 
    [intellij-stdout] Info  | RdCoroutineScope          | 11:JobScheduler FJ pool 0/3 | RdCoroutineHost overridden 
    request[project/open]: "/tmp/machete-tests-410347444574336497/machete-sandbox-worktree"
    [intellij-stdout] opened com.intellij.openapi.wm.impl.IdeFrameImpl
    [intellij-stdout] closed Welcome to IntelliJ IDEA (ROOT)
    [intellij-stdout] 2022-08-22 10:29:23,094 [  13591]   WARN - ctionSystem.impl.ActionUpdater - 848 ms to grab EDT for CWMTelephonyGroup#update (com.jetbrains.rd.platform.codeWithMe.telephony.CWMTelephonyGroup) 
    response: ()
    Waiting for 3 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0, ProgressIndicatorEx 1289239017: running=true; canceled=false; reusable=true, ProgressIndicatorEx 989899735: running=true; canceled=false; reusable=true]
    [intellij-stdout] 2022-08-22 10:29:23,810 [  14307]   WARN - ctionSystem.impl.ActionUpdater - 104 ms to call on EDT SyncProjectAction#update (com.android.tools.idea.gradle.actions.SyncProjectAction). Use `UpdateInBackground`. 
    [intellij-stdout] 2022-08-22 10:29:24,531 [  15028]   WARN - ctionSystem.impl.ActionUpdater - 270 ms to grab EDT for OpenFileAction#update (com.intellij.ide.actions.OpenFileAction) 
    [intellij-stdout] 2022-08-22 10:29:24,532 [  15029]   WARN - ctionSystem.impl.ActionUpdater - 236 ms to grab EDT for CWMTelephonyGroup#update (com.jetbrains.rd.platform.codeWithMe.telephony.CWMTelephonyGroup) 
    [intellij-stdout] opened javax.swing.JWindow
    [intellij-stdout] 2022-08-22 10:29:26,079 [  16576]   WARN - ctionSystem.impl.ActionUpdater - 1362 ms to grab EDT for SpaceMainToolBarAction#update (com.intellij.space.actions.SpaceMainToolBarAction) 
    [intellij-stdout] 2022-08-22 10:29:26,081 [  16578]   WARN - ctionSystem.impl.ActionUpdater - 1359 ms to grab EDT for CWMTelephonyGroup#update (com.jetbrains.rd.platform.codeWithMe.telephony.CWMTelephonyGroup) 
    Waiting for 1 background task(s)... [Dependencies 1626944612: running=true; canceled=false; task=com.jetbrains.packagesearch.intellij.plugin.util.CoroutinesUtilsKt$showBackgroundLoadingBar$2@411d65b]
    runJs: executing `project.configure()`
    runJs: executed `project.configure()`
    request[projects/all]: ()
    response: [{"name":"machete-sandbox-worktree"}]
    runJs: executing `project.openGitMacheteTab()`
    runJs: executed `project.openGitMacheteTab()`
    runJs: executing `project.toolbar.toggleListingCommits()`
    [intellij-stdout] closed javax.swing.JWindow
    [intellij-stdout] 2022-08-22 10:29:38,835 [  29332]   WARN - ctionSystem.impl.ActionUpdater - 761 ms to grab EDT for ResetCurrentToRemoteAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.ResetCurrentToRemoteAction) 
    [intellij-stdout] 2022-08-22 10:29:38,835 [  29332]   WARN - ctionSystem.impl.ActionUpdater - 761 ms to grab EDT for ApplyChangesAction#update (com.android.tools.idea.run.ui.ApplyChangesAction) 
    runJs: executed `project.toolbar.toggleListingCommits()`
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `18`
    runJs: executing `project.checkoutBranch('call-ws')`
    runJs: executed `project.checkoutBranch('call-ws')`
    Waiting for 1 background task(s)... [Checking out 912835622: running=true; canceled=false; task=com.virtuslab.gitmachete.frontend.actions.contextmenu.CheckoutSelectedAction$1@4f4accf8]
    [intellij-stdout] 2022-08-22 10:29:44,947 [  35444]   WARN - ernallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree 
    runJs: executing `project.toolbar.squash()`
    runJs: executed `project.toolbar.squash()`
    Waiting for 1 background task(s)... [com.intellij.openapi.progress.EmptyProgressIndicator@ebb8834]
    [intellij-stdout] opened Squashed Commit Message:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,1742,932,355x295,invalid,layout=java.awt.BorderLayout,MODELESS,title=Squashed Commit Message,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,355x295,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]
    Waiting for 1 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0]
    runJs: executing `project.acceptSquash()`
    [intellij-stdout] closed Squashed Commit Message
    runJs: executed `project.acceptSquash()`
    Waiting for 1 background task(s)... [Squashing 521373407: running=true; canceled=false; task=com.virtuslab.gitmachete.frontend.actions.base.BaseSquashAction$1@45637844]
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `16`
    runJs: executing `project.findCellAndRightClick('hotfix/add-trigger')`
    [intellij-stdout] opened javax.swing.Popup$HeavyWeightWindow
    [intellij-stdout] 2022-08-22 10:30:17,756 [  68253]   WARN - ernallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree 
    runJs: executed `project.findCellAndRightClick('hotfix/add-trigger')`
    runJs: executing `project.contextMenu.checkoutAndSquash()`
    [intellij-stdout] closed javax.swing.Popup$HeavyWeightWindow
    [intellij-stdout] opened Squashed Commit Message:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog1,0,0,462x229,invalid,layout=java.awt.BorderLayout,MODELESS,title=Squashed Commit Message,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,462x229,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]
    runJs: executed `project.contextMenu.checkoutAndSquash()`
    runJs: executing `project.acceptSquash()`
    runJs: executed `project.acceptSquash()`
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `16`
    runJs: executing `ide.closeOpenedProjects()`
    [intellij-stdout] project to close = Project(name=machete-sandbox-worktree, containerState=COMPONENT_CREATED, componentStore=/tmp/machete-tests-410347444574336497/machete-sandbox-worktree)
    [intellij-stdout] 2022-08-22 10:30:32,205 [  82702]   WARN - com.intellij.util.xmlb.Binding - no accessors for org.jetbrains.idea.perforce.perforce.ConnectionId 
    runJs: executed `ide.closeOpenedProjects()`

com.virtuslab.gitmachete.uitest.UITestSuite > squashBranch FAILED
    java.lang.AssertionError: expected:<15> but was:<16>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at com.virtuslab.gitmachete.uitest.UITestSuite.squashBranch(UITestSuite.scala:240)
```

Would be good to list the commit messages in test stdout, so that we can see what's the superfluous commit.

**Comment by PawelLipski** [comment]
Rarely failing after we've gone back to invoking actions explicitly (instead of clicking on buttons)... closing

**Comment by PawelLipski** [comment]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/7640/workflows/ec66e612-e7b5-4c86-802f-93ca34ca95a2/jobs/8059

**Comment by PawelLipski** [comment]
Haven't seen for a while... closing (again) :trollface:

**Comment by PawelLipski** [comment]
Ha! _hello darkness my old friend_

https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/8669/workflows/455be7d5-47e9-47a0-84c2-83e2e45838a5/jobs/9093

```expected: <List(develop, Allow ownership links, allow-ownership-link, Use new icons, 1st round of fixes, update-icons, Build arbitrarily long chains, Use new icons, 1st round of fixes, build-chain, Call web service, call-ws, master, HOTFIX Add the trigger, hotfix/add-trigger)> but was: <ArraySeq(develop, Allow ownership links, allow-ownership-link, Use new icons, 1st round of fixes, update-icons, Build arbitrarily long chains, Use new icons, 1st round of fixes, build-chain, Call web service, call-ws, master, HOTFIX Add the trigger - fixes, HOTFIX Add the trigger, hotfix/add-trigger)>
```

The difference is in the unexpected presence of `HOTFIX Add the trigger - fixes` commit 🤔

**Comment by PawelLipski** [comment]
Closing for now, to be reopened if reoccurs

**Comment by PawelLipski** [comment]
☹️ https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/8967/workflows/9fb610d7-2f71-41f8-a50c-0683b41381e6/jobs/9398/steps

Stuck forever waiting for 15 elements (rather than 16)... so the issue is that the squash **doesn't** actually happen at all for some reason ‼️

**Comment by PawelLipski** [comment]
FWIW... let's track the IDE logs from around the moment where the Squash action on `hotfix/add-trigger` failed to execute (?), right after that very same action on `call-ws` passed:

```
2023-02-19 17:01:11,854 [  37328]   INFO - STDOUT - opened Squashed Commit Message:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,1742,932,355x295,invalid,layout=java.awt.BorderLayout,MODELESS,title=Squashed Commit Message,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,355x295,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]
2023-02-19 17:01:12,556 [  38030]   INFO - com.virtuslab.gitmachete.frontend.actions.toolbar.SquashCurrentAction - Checking out 'call-ws' branch and squashing it
2023-02-19 17:01:14,015 [  39489]   INFO - #git4idea.rebase.GitRebaseProcess - Started rebase
2023-02-19 17:01:14,024 [  39498]   INFO - #git4idea.rebase.GitRebaseProcess - Rebasing root machete-sandbox-worktree, mode: standard
2023-02-19 17:01:14,035 [  39509]   INFO - #git4idea.commands.GitHandler - [machete-sandbox-worktree] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false -c core.commentChar= rebase --interactive --no-autosquash 5aef9960ea2bb9b3da88275a105185b8de856430
2023-02-19 17:01:14,698 [  40172]   INFO - STDOUT - closed Squashed Commit Message
2023-02-19 17:01:14,818 [  40292]   INFO - #git4idea.commands.GitHandler - Successfully rebased and updated refs/heads/call-ws.
2023-02-19 17:01:14,870 [  40344]   INFO - #c.i.o.v.c.VcsShelveChangesSaver - load
2023-02-19 17:01:14,904 [  40378]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - Indexing 1 commits in machete-sandbox-worktree
2023-02-19 17:01:14,943 [  40417]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - 36ms for indexing 1 new commits out of 1 in machete-sandbox-worktree
2023-02-19 17:01:24,312 [  49786]   INFO - STDOUT - opened Squashed Commit Message:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog1,0,0,462x229,invalid,layout=java.awt.BorderLayout,MODELESS,title=Squashed Commit Message,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,462x229,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]
2023-02-19 17:01:24,384 [  49858]   WARN - #c.i.o.v.ExternallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree
2023-02-19 17:01:29,287 [  54761]   INFO - STDOUT - project to close = Project(name=machete-sandbox-worktree, containerState=COMPONENT_CREATED, componentStore=/tmp/machete-tests-6573088583850894401/machete-sandbox-worktree)
2023-02-19 17:01:29,437 [  54911]   WARN - #c.i.u.x.Binding - no accessors for org.jetbrains.idea.perforce.perforce.ConnectionId
2023-02-19 17:01:29,682 [  55156]   INFO - #c.j.r.f.FollowMeManager - Unregister user 0:'root' with ClientId=ClientId(value=Host)
2023-02-19 17:01:29,696 [  55170]   INFO - #c.i.u.i.UnindexedFilesScanner - 6ab3a8fd: cancelling initial VFS refresh
2023-02-19 17:01:29,710 [  55184]   INFO - #c.i.c.b.CompilerReferenceServiceBase - backward reference index reader is closed (didn't exist)
2023-02-19 17:01:29,710 [  55184]   INFO - #o.j.k.i.s.r.KotlinCompilerReferenceIndexStorage - KCRI storage is closed (didn't exist)
2023-02-19 17:01:29,718 [  55192]   INFO - #c.i.o.p.i.CoreProgressManager - Task canceled because of project disposal: git4idea.vfs.GitVFSListener$1@41ead94f
2023-02-19 17:01:30,717 [  56191]   INFO - STDOUT - closed Squashed Commit Message
2023-02-19 17:01:31,412 [  56886]   INFO - STDOUT - closed com.intellij.openapi.wm.impl.IdeFrameImpl
```

**Comment by PawelLipski** [comment]
Long time no see! [CI build](https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/9891/workflows/4656cfb3-20c3-4588-b835-dd32c30d0959/jobs/10330/tests)

```
org.opentest4j.AssertionFailedError: expected: <List(develop, Allow ownership links, allow-ownership-link, Use new icons, 1st round of fixes, update-icons, Build arbitrarily long chains, Use new icons, 1st round of fixes, build-chain, Call web service, call-ws, master, HOTFIX Add the trigger, hotfix/add-trigger)> but was: <ArraySeq(develop, Allow ownership links, allow-ownership-link, Use new icons, 1st round of fixes, update-icons, Build arbitrarily long chains, Use new icons, 1st round of fixes, build-chain, Call web service, call-ws, master, HOTFIX Add the trigger - fixes, HOTFIX Add the trigger, hotfix/add-trigger)>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at com.virtuslab.gitmachete.uitest.UITestSuite.squashBranch(UITestSuite.scala:313)
```

**Comment by PawelLipski** [comment]
I guess that doing https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1728 might fix this flakiness as a side effect ;)
