### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service git4idea.repo.GitRepositoryManager because container is already disposed (container=Project(name=spring-microv2, containerState=DISPOSE_COMPLETED, componentStore=/home/danimayday/BackUpLinux/IdeaProjects/LEARN/spring-microv2) (disposed))

### ISSUE THREAD

**Issue by yeahbutstill** [VirtusLab/git-machete-intellij-plugin#1091]
## Running environment
- Git Machete plugin version - 2.2.0
- IDE - IntelliJ IDEA 2022.2.1
- Operating system - Linux 5.15.0-46-generic

## IDEA - stack trace
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service git4idea.repo.GitRepositoryManager because container is already disposed (container=Project(name=spring-microv2, containerState=DISPOSE_COMPLETED, componentStore=/home/danimayday/BackUpLinux/IdeaProjects/LEARN/spring-microv2) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:685)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:658)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:621)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at git4idea.repo.GitRepositoryManager.getInstance(GitRepositoryManager.java:50)
	at git4idea.GitUtil.getRepositoryManager(GitUtil.java:615)
	at git4idea.GitUtil.getRepositories(GitUtil.java:863)
	at com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox.updateRepositories(GitRepositoryComboBox.java:62)
	at com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox.lambda$new$0(GitRepositoryComboBox.java:47)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

## IDEA - additional info
N/A

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Logs
Enable logging on DEBUG level for this plugin by adding
```
com.virtuslab
```
to the list under `Help` -> `Diagnostic Tools` -> `Debug Log Settings`.<br/>
Then reproduce a bug and attach the logs to the issue.<br/>
To find IntelliJ log file, go to `Help` -> `Show Log in Files`.

Consider placing the logs within the `details` (aka "spoiler") tags as the may be very extensive.

<details>
<summary>Logs</summary>
Logs go here
</details>

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

**Comment by PawelLipski** [comment]
Thanks for reporting... looks like good old friend that we've (mostly) beaten in #811. @mkondratek can you check whether fixing it is within our reach, or the fix needs to be done on git4idea codebase directly?

**Comment by mkondratek** [comment]
I ve reviewed the code. We had that fixed on our end (message bus connection registered to the disposer).

https://github.com/VirtusLab/git-machete-intellij-plugin/blob/28fd7c8591ecdef3e0dde0e10669c5b7bbe51217/frontendUiImpl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/gitrepositoryselection/GitRepositoryComboBox.java#L43-L49

So I guess this is a problem on `git4idea` side. I suggest closing this one for now (as it rather seems to be a sporadic issue). In case it reappears we will do a more extensive investigation.

**Comment by PawelLipski** [comment]
+1, closing then
