### ISSUE TITLE
Revisit the primitive `prohibit-kotlin-private-fields` check

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1131]
- [x] Is the concern still valid under the version(s) of Kotlin that the plugin might encounter [in the supported IDE versions](https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library)? I've established that the problem is https://youtrack.jetbrains.com/issue/KT-29016 ... but actually that issue doesn't speak about private fields, so maybe I was wrong. Generally, pls explore the possible bugs around the area of reflective access to properties. I'd suggest checking the entire Cartesian product of class/val access modifiers (plus maybe some third axis, TBD) within a test under `src/test/`, so that we can reproduce the findings in the future, against different Kotlin versions.
- [x] Consider refining the check against whatever is the unsafe construct (if anything), using ArchUnit. Might be tricky since the check needs to be done [on Kotlin classes only](https://stackoverflow.com/questions/39806721/i-want-to-detect-if-a-jvm-class-is-a-kotlin-class-or-not).
- [x] Consider converting public properties in Kotlin code to private wherever it makes sense

**Comment by PawelLipski** [comment]
For the record, the original error used to be:

```
2022-09-18 18:21:12,883 [  24444]  ERROR - pplication.impl.LaterInvocator - java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog with modifiers "private" 
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog with modifiers "private"
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:224)
        at kotlin.reflect.jvm.internal.KProperty0Impl.get(KProperty0Impl.kt:35)
        at kotlin.reflect.jvm.internal.KProperty0Impl$Getter.invoke(KProperty0Impl.kt:44)
        at com.intellij.ui.layout.Cell.checkBox(Cell.kt:286)
        at com.intellij.ui.layout.Cell.checkBox(Cell.kt:276)
        at com.intellij.ui.layout.Cell.checkBox$default(Cell.kt:275)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog$createCenterPanel$1$3.invoke(DeleteBranchOnSlideOutSuggestionDialog.kt:77)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog$createCenterPanel$1$3.invoke(DeleteBranchOnSlideOutSuggestionDialog.kt:76)
        at com.intellij.ui.layout.RowBuilder$DefaultImpls.row(Row.kt:42)
        at com.intellij.ui.layout.Row.row(Row.kt:107)
        at com.intellij.ui.layout.LayoutBuilder.row(LayoutBuilder.kt)
        at com.intellij.ui.layout.RowBuilder$DefaultImpls.row$default(Row.kt:41)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog.createCenterPanel(DeleteBranchOnSlideOutSuggestionDialog.kt:76)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog.createCenterPanel(DeleteBranchOnSlideOutSuggestionDialog.kt:18)
        at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1331)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog.<init>(DeleteBranchOnSlideOutSuggestionDialog.kt:27)
        at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.suggestBranchDeletion(BaseSlideOutBranchAction.java:140)
        at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.lambda$deleteBranchIfRequired$3(BaseSlideOutBranchAction.java:125)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog with modifiers "private"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
        at java.base/java.lang.reflect.Field.get(Field.java:416)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance.call(CallerImpl.kt:179)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        ... 46 more
```

Doesn't seem to be a problem anymore as we switched to Kotlin UI DSL v2. Still, even with the newer versions of Kotlin, it's still possible to get `IllegalCallableAccessException` (even if we might not encounter it coming from the IntelliJ APIs we're using). Lemme add a test that would showcase the repro.

**Comment by PawelLipski** [comment]
For the record, the original error used to be:

```
2022-09-18 18:21:12,883 [  24444]  ERROR - pplication.impl.LaterInvocator - java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog with modifiers "private" 
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog with modifiers "private"
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:224)
        at kotlin.reflect.jvm.internal.KProperty0Impl.get(KProperty0Impl.kt:35)
        at kotlin.reflect.jvm.internal.KProperty0Impl$Getter.invoke(KProperty0Impl.kt:44)
        at com.intellij.ui.layout.Cell.checkBox(Cell.kt:286)
        at com.intellij.ui.layout.Cell.checkBox(Cell.kt:276)
        at com.intellij.ui.layout.Cell.checkBox$default(Cell.kt:275)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog$createCenterPanel$1$3.invoke(DeleteBranchOnSlideOutSuggestionDialog.kt:77)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog$createCenterPanel$1$3.invoke(DeleteBranchOnSlideOutSuggestionDialog.kt:76)
        at com.intellij.ui.layout.RowBuilder$DefaultImpls.row(Row.kt:42)
        at com.intellij.ui.layout.Row.row(Row.kt:107)
        at com.intellij.ui.layout.LayoutBuilder.row(LayoutBuilder.kt)
        at com.intellij.ui.layout.RowBuilder$DefaultImpls.row$default(Row.kt:41)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog.createCenterPanel(DeleteBranchOnSlideOutSuggestionDialog.kt:76)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog.createCenterPanel(DeleteBranchOnSlideOutSuggestionDialog.kt:18)
        at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1331)
        at com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog.<init>(DeleteBranchOnSlideOutSuggestionDialog.kt:27)
        at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.suggestBranchDeletion(BaseSlideOutBranchAction.java:140)
        at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.lambda$deleteBranchIfRequired$3(BaseSlideOutBranchAction.java:125)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class com.virtuslab.gitmachete.frontend.actions.dialogs.DeleteBranchOnSlideOutSuggestionDialog with modifiers "private"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
        at java.base/java.lang.reflect.Field.get(Field.java:416)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance.call(CallerImpl.kt:179)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        ... 46 more
```

Doesn't seem to be a problem anymore as we switched to Kotlin UI DSL v2. Still, even with the newer versions of Kotlin, it's still possible to get `IllegalCallableAccessException` (even if we might not encounter it coming from the IntelliJ APIs we're using). Lemme add a test that would showcase the repro.
