### ISSUE TITLE
`GitCoreRepository.isBranchPresent` throws "Not a directory" exception for local branch

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/git-machete-intellij-plugin#1298]
Reproduce steps:
1. Create a new local branch in repository `A` (it should not exist remotely - only locally)
2. Open `A` as a project in IntelliJ IDEA
3. Open Machete File
4. Boom! Ide error appears.

In my case - the branch's name was `docs/improve_reference_conf_comments`. This exception looks like a false positive. It should not be displayed as an error.

Stacktrace:
```
java.nio.file.FileSystemException: /Users/lkontowski/code/ide-probe/.git/refs/remotes/upstream/docs/improve_reference_conf_comments: Not a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at org.eclipse.jgit.util.FileUtils.fileAttributes(FileUtils.java:804)
	at org.eclipse.jgit.util.FS.fileAttributes(FS.java:1268)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:234)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:213)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:104)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.lambda$1(RefDirectory.java:1095)
	at org.eclipse.jgit.util.FileUtils.readWithRetries(FileUtils.java:722)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.scanRef(RefDirectory.java:1094)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.readRef(RefDirectory.java:1052)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.readAndResolve(RefDirectory.java:263)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.firstExactRef(RefDirectory.java:317)
	at org.eclipse.jgit.lib.RefDatabase.findRef(RefDatabase.java:271)
	at org.eclipse.jgit.lib.Repository.findRef(Repository.java:1094)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:811)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:472)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$isBranchPresent$3f19b513$1(GitCoreRepository.java:137)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.isBranchPresent(GitCoreRepository.java:137)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveRemoteBranchByName(GitCoreRepository.java:278)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveInferredRemoteBranchForLocalBranch(GitCoreRepository.java:384)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveRemoteBranchForLocalBranch$ff082a48$1(GitCoreRepository.java:353)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveRemoteBranchForLocalBranch(GitCoreRepository.java:353)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveAllLocalBranches$d9482c2f$1(GitCoreRepository.java:309)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveAllLocalBranches$11(GitCoreRepository.java:298)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveAllLocalBranches(GitCoreRepository.java:313)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$Aux.<init>(GitMacheteRepository.java:124)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.<init>(GitMacheteRepository.java:304)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout(GitMacheteRepository.java:80)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.lambda$updateRepositorySnapshot$ebc90931$1(GitMacheteRepositoryUpdateBackgroundable.java:94)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.updateRepositorySnapshot(GitMacheteRepositoryUpdateBackgroundable.java:91)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.run(GitMacheteRepositoryUpdateBackgroundable.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:426)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:667)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by PawelLipski** [comment]
Actually... this looks pretty unexpected... is it always reproducible with just the 4 steps you've listed above? we'd surely encounter it many more times 🤔 anyway, pls share your .git/ directory (TBD how to do it, depending on the zipped size), as it might be an issue specific to the particular setup in this repo

**Comment by PawelLipski** [comment]
Or even before that... pls share `.git/machete` and `find /Users/lkontowski/code/ide-probe/.git/refs/`

**Comment by LukaszKontowski** [comment]
1. Machete file content:
```
% cat .git/machete
master
	bundled-plugins-fix
	docs/improve_reference_conf_comments
	feature/automated_intellij_version_bump
	feature/install_ide_from_dmg
	fix/disable_verbose_git_pull_output
	fix/intellij-snapshot-resolving-patterns
	fix/intellij_version_PR_comment
	fix/make_idea_logs_accessible_after_shutdown
	fix/update_intellij_version_PRs
	test_is_ci_check
```

**Comment by LukaszKontowski** [comment]
2. `.git/refs/` contents:
```
% find /Users/lkontowski/code/ide-probe/.git/refs/
/Users/lkontowski/code/ide-probe/.git/refs/
/Users/lkontowski/code/ide-probe/.git/refs//heads
/Users/lkontowski/code/ide-probe/.git/refs//heads/docs
/Users/lkontowski/code/ide-probe/.git/refs//heads/docs/improve_reference_conf_comments
/Users/lkontowski/code/ide-probe/.git/refs//heads/master
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/disable_verbose_git_pull_output
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/probe_resolvers_jbr_repositories
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/macOS_local_tests
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/sbt-idea-plugin
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/case_class_Jar_handling
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/confusing_error_dir_path
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/osx_intellij_version_resolver_version
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/make_idea_logs_accessible_after_shutdown
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/local_sbt_test
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/intellij_version_PR_comment
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/update_intellij_version_PRs
/Users/lkontowski/code/ide-probe/.git/refs//heads/fix/intellij-snapshot-resolving-patterns
/Users/lkontowski/code/ide-probe/.git/refs//heads/feature
/Users/lkontowski/code/ide-probe/.git/refs//heads/feature/automated_intellij_version_bump
/Users/lkontowski/code/ide-probe/.git/refs//heads/feature/remote_robot_configurable
/Users/lkontowski/code/ide-probe/.git/refs//heads/feature/allow_for_globs_repositories_config
/Users/lkontowski/code/ide-probe/.git/refs//heads/feature/create_display_mode_config
/Users/lkontowski/code/ide-probe/.git/refs//heads/feature/install_ide_from_dmg
/Users/lkontowski/code/ide-probe/.git/refs//heads/bundled-plugins-fix
/Users/lkontowski/code/ide-probe/.git/refs//heads/unused_warnings_fix
/Users/lkontowski/code/ide-probe/.git/refs//heads/test_is_ci_check
/Users/lkontowski/code/ide-probe/.git/refs//tags
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.7.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.23.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.29.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.42.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.1.2
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.9.1
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.1.3
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.46.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.9.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.27.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.3.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.18.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.12.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.37.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.33.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.39.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.10.2
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.16.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.2.2
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.20.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.4.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.41.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.45.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.24.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.20.1
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.34.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.11.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.15.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.30.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.40.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.5.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.21.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.25.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.44.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.35.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.10.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.14.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.10.1
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.31.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.43.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.28.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.22.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.6.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.2.1
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.2.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.26.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.13.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.19.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.36.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.38.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.32.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.13.1
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.17.0
/Users/lkontowski/code/ide-probe/.git/refs//tags/v0.36.1
/Users/lkontowski/code/ide-probe/.git/refs//remotes
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/update_intellij_version
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/update_intellij_version/2022.2.3
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/HEAD
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/master
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/disable_verbose_git_pull_output
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/probe_resolvers_jbr_repositories
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/sbt-idea-plugin
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/case_class_Jar_handling
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/newest_intellij_release_tests
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/confusing_error_dir_path
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/replace_is_accessible
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/make_idea_logs_accessible_after_shutdown
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/intellij_version_PR_comment
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/update_intellij_version_PRs
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/fix/intellij-snapshot-resolving-patterns
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/enable_globs_in_repositories_config
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/automated_intellij_version_bump
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/exclude_errors_by_parts_of_stack_trace
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/replace_fixture_defaults_with_conf
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/allow_for_globs_repositories_config
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/create_display_mode_config
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/install_ide_from_dmg
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/replace_IntelliJ_Fixture_defaults_with_conf
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/feature/create_default_conf
/Users/lkontowski/code/ide-probe/.git/refs//remotes/origin/unused_warnings_fix
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bazel-tests
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/remote-robot-0.11.5
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/from-2020.3
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/2021.2-support
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bump-robot
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bazel-validate-dirs
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/run-no-stuck
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/no-apply
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/reuse-ws
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/policy-2021
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/scala-ext-212
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/2020.3-rebased
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bench
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/ide-message-fix
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bsp-bug-repro
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/fix-tests
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/build-plugin-fix
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bump-ij
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/update_intellij_version
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/update_intellij_version/2022.2.3
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/highlighting
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/disable-debug-mode-on-CI
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/consents
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/junit
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/improvements
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/robot-url-overridable
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/jbr
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/use-scala-master
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/203
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bazel-open-project-keep-view-file
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/sdk-api
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/wait-logic
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/read-artifact-build
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/release-tool-compat
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/vcs-roots
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/reenable-tests
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/no-cross
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/read-nav-target
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/screenshot-fail
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/docs
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/override-plugins
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/robot
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/extensions
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/java-8-compat
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/resolvers
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/inspections
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/modules-api
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/2020.3
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/prefetch-dependencies-in-docker
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bazel-build
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/cleanup
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/robot-cache
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/multi-plugin-resolver
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/master
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/ci-release-bump
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/mb
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/mb/examples-followup
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/mb/fix-test-config
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/mb/example
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/mb/examples
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/setsid-once
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/run-args
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/notification-timeout
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/trust
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/custom-params
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/shorten-cmdline
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/run-ij-hook
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/mutable-factories
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bsp-fastpass-test
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/fix-dmg
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/run
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/run/configurations
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/scalafmt
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bsp-import
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/showcase
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/content-roots-simplify
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bundled-plugins-fix
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/sbt-test
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/bazel-build-config
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/policy-euacommunity-2021
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/package-prefix
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/logging
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/await-idle-defaults
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/wait-exact
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/builders-api
/Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/await-idle-driver-side
```

**Comment by PawelLipski** [comment]
Okay... one more thing, `ls -l /Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/docs`... I suppose it's a regular file, not a directory right?

**Comment by LukaszKontowski** [comment]
> is it always reproducible with just the 4 steps you've listed above? 

No, I did not manage to reproduce it on other repository. 🤔 Maybe it could be connected to the fact that the repo where I had this bug is a forked repository? I don't know. It looks strange, because mentioned branch exists under /.git/refs//heads/:
`/Users/lkontowski/code/ide-probe/.git/refs//heads/docs/improve_reference_conf_comments`
but for some reason the exception tries to find it under `/.git/refs/remotes/`

**Comment by LukaszKontowski** [comment]
```
% ls -l /Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/docs
-rw-r--r--  1 lkontowski  staff  41 Aug  5 10:56 /Users/lkontowski/code/ide-probe/.git/refs//remotes/upstream/docs
```
It is a regular file...

**Comment by PawelLipski** [comment]
Okay, just so that the repro isn't lost, pls share your .git/ anyway... what's its zipped size? is it more like MBs or 100s of MBs?

**Comment by LukaszKontowski** [comment]
Hm, I just realized that probably the problem might be that **there is** a branch named `docs` on the upstream of `ide-probe`: https://github.com/VirtusLab/ide-probe/tree/docs
...
So, maybe that's the reason. Branches like `docs/improve_reference_conf_comments` should not be created as it such naming leads to unexpected errors?

**Comment by LukaszKontowski** [comment]
[ide-probe-git.zip](https://github.com/VirtusLab/git-machete-intellij-plugin/files/9851209/ide-probe-git.zip)
~ 3,5 Mb

**Comment by PawelLipski** [comment]
Whoever picks up this task... let's also check if git-machete CLI is affected

**Comment by PawelLipski** [comment]
That's even more surprising given that `Try.of(...)` is supposed to capture the error 🤔 

The fact that it's been logged is probably due to a call to `LOG.<method>(..., e)` somewhere in the internals of JGit... which IIRC also causes an error to be logged by IDE (but probably only `LOG.error(..., e)` is affected, to be checked). Needs to be checked under a debugger probably, might be hard to pinpoint otherwise.

**Comment by LukaszKontowski** [comment]
Here is the problematic place:
`at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:234)`
Indeed - it contains
```
...
} catch (IOException e) {
    LOG.error(e.getMessage(), e);
...
```
So, your guess is right.

**Comment by PawelLipski** [comment]
Huh okay... pls check what implementation is bound at runtime to this `LOG.error(..., e)` and whether its behavior is even remotely configurable (I suppose the answer is **no** xD).

And as a workaround... we can't really forbid having `refs/heads/foo/bar` and `refs/remotes/origin/foo` in a single repo. What I'd do is defensively reimplement `GitCoreRepository.isBranchPresent` (and probably some other methods, TBD) in the following manner:

```
isBranchPresent(branchName):
  for each `/`-separated prefix P of `branchName`:
  # like, `foo`, `foo/bar`, `foo/bar/qux` for `foo/bar/qux/lol`
    if branch called P exists:
    # then surely `branchName` cannot exist, and we'll avoid a failing call to `FileSnapshot.<init>`
      return false
    return whether `branchName` exists
```

This is a scratch implementation, to be proof-read and tested ;)
