### ISSUE TITLE
java.lang.IllegalStateException: Index is not created for `Stubs`

### ISSUE THREAD

**Issue by Archsx** [VirtusLab/git-machete-intellij-plugin#1388]
## Running environment
- Git Machete plugin version - 3.2.2
- IDE - IntelliJ IDEA 2022.2.3
- Operating system - Linux 5.15.0-56-generic

## IDEA - stack trace
```
failed to open shared index: extension = Stubs, chunk = org_apache_httpcomponents_httpcore_4_4_14-9c397d058d394075ed833e713685343768dca8c6dca43d21fec06540a467ed8c-7f43855cd362

java.lang.IllegalStateException: Index is not created for `Stubs`
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndex(FileBasedIndexImpl.java:1307)...
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Git Machete, id=com.virtuslab.git-machete, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.2/git-machete-intellij-plugin, version=3.2.2, package=null, isBundled=false), packagePrefix=null, instanceId=374, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:844)
	... 48 more
```

## IDEA - additional info
N/A

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Logs
Enable logging on DEBUG level for this plugin by adding
```
com.virtuslab
```
to the list under `Help` -> `Diagnostic Tools` -> `Debug Log Settings`.<br/>
Then reproduce a bug and attach the logs to the issue.<br/>
To find IntelliJ log file, go to `Help` -> `Show Log in Files`.

Consider placing the logs within the `details` (aka "spoiler") tags as the may be very extensive.

<details>
<summary>Logs</summary>
Logs go here
</details>

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

**Comment by PawelLipski** [comment]
Wow looks like a race condition in IDEA itself... thanks for reporting, we'll see whether it's within our powers to prevent such errors 🐞

**Comment by Archsx** [comment]
> Wow looks like a race condition in IDEA itself... thanks for reporting, we'll see whether it's within our powers to prevent such errors lady_beetle

Hi, I have to apologize that this issue seems to be caused by the fact that I installed the plugin from market but the network is slow so I downloaded from browser and installed from disk again.

**Comment by PawelLipski** [comment]
Wow okay... still surprising tho 🤔 anyway, good to hear it works finally!
