### ISSUE TITLE
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot create class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Git Machete, id=com.virtuslab.git-machete, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.2/git-machete-intellij-plugin, version=3.2.2, package=null, isBundled=false), packagePrefix=null, instanceId=374, state=active))

### ISSUE THREAD

**Issue by Archsx** [VirtusLab/git-machete-intellij-plugin#1389]
## Running environment
- Git Machete plugin version - 3.2.2
- IDE - IntelliJ IDEA 2022.2.3
- Operating system - Linux 5.15.0-56-generic

## IDEA - stack trace
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot create class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Git Machete, id=com.virtuslab.git-machete, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.2/git-machete-intellij-plugin, version=3.2.2, package=null, isBundled=false), packagePrefix=null, instanceId=374, state=active))
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)...
Caused by: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot create class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Git Machete, id=com.virtuslab.git-machete, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.2/git-machete-intellij-plugin, version=3.2.2, package=null, isBundled=false), packagePrefix=null, instanceId=374, state=active))
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)...
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Git Machete, id=com.virtuslab.git-machete, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.2/git-machete-intellij-plugin, version=3.2.2, package=null, isBundled=false), packagePrefix=null, instanceId=374, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.virtuslab.gitmachete.frontend.file.grammar.MacheteParserDefinition
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:844)
	... 48 more
```

## IDEA - additional info
N/A

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Logs
Enable logging on DEBUG level for this plugin by adding
```
com.virtuslab
```
to the list under `Help` -> `Diagnostic Tools` -> `Debug Log Settings`.<br/>
Then reproduce a bug and attach the logs to the issue.<br/>
To find IntelliJ log file, go to `Help` -> `Show Log in Files`.

Consider placing the logs within the `details` (aka "spoiler") tags as the may be very extensive.

<details>
<summary>Logs</summary>
Logs go here
</details>

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

**Comment by PawelLipski** [comment]
Huh not good ☹️ @Archsx are these errors deterministic? were you **ever** able to use the plugin v3.2.2 (or earlier) under your IDE version?

**Comment by Archsx** [comment]
> Huh not good frowning_face @Archsx are these errors deterministic? were you **ever** able to use the plugin v3.2.2 (or earlier) under your IDE version?

hi, it is my first time to install machete, but it cause some error that I could not even open *Plugin* panel. I have to disabled it .  :(
