### ISSUE TITLE
Error on development ide startup - 'modalComponent' must not be null

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#1462]
## Question or problem description

It happens when I try to open machete-sandbox project

<details>
<summary>log</summary>

```java
09:19:50: Executing 'runIde'...

Starting Gradle Daemon...
Connected to the target VM, address: '127.0.0.1:63543', transport: 'socket'
Gradle Daemon started in 780 ms
> Task :buildSrc:spotlessInternalRegisterDependencies UP-TO-DATE
> Task :buildSrc:spotlessKotlin UP-TO-DATE
> Task :buildSrc:spotlessKotlinApply UP-TO-DATE
> Task :buildSrc:spotlessKotlinGradle UP-TO-DATE
> Task :buildSrc:spotlessKotlinGradleApply UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:spotlessKotlinCheck UP-TO-DATE
> Task :buildSrc:spotlessKotlinGradleCheck UP-TO-DATE
> Task :buildSrc:spotlessCheck UP-TO-DATE
> Task :buildSrc:compileTestKotlin UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test UP-TO-DATE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :frontend:actions:patchPluginXml SKIPPED
> Task :frontend:actions:verifyPluginConfiguration SKIPPED
> Task :spotlessInternalRegisterDependencies UP-TO-DATE
> Task :backend:impl:createCheckerFrameworkManifest UP-TO-DATE
> Task :frontend:base:createCheckerFrameworkManifest UP-TO-DATE
> Task :binding:createCheckerFrameworkManifest UP-TO-DATE
> Task :branchLayout:api:createCheckerFrameworkManifest UP-TO-DATE
> Task :qual:createCheckerFrameworkManifest UP-TO-DATE
> Task :frontend:file:createCheckerFrameworkManifest UP-TO-DATE
> Task :gitCore:api:createCheckerFrameworkManifest UP-TO-DATE
> Task :backend:api:createCheckerFrameworkManifest UP-TO-DATE
> Task :branchLayout:impl:createCheckerFrameworkManifest UP-TO-DATE
> Task :frontend:actions:spotlessKotlin UP-TO-DATE
> Task :frontend:actions:spotlessKotlinApply UP-TO-DATE
> Task :binding:spotlessJava UP-TO-DATE
> Task :binding:spotlessJavaApply UP-TO-DATE
> Task :frontend:file:generateParser UP-TO-DATE
> Task :gitCore:api:spotlessJava UP-TO-DATE
> Task :binding:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:file:generateLexer UP-TO-DATE
> Task :gitCore:api:spotlessJavaApply UP-TO-DATE
> Task :binding:spotlessKotlinGradleApply UP-TO-DATE
> Task :backend:api:spotlessJava UP-TO-DATE
> Task :backend:api:spotlessJavaApply UP-TO-DATE
> Task :gitCore:api:spotlessKotlinGradle UP-TO-DATE
> Task :gitCore:api:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:resourcebundles:createCheckerFrameworkManifest UP-TO-DATE
> Task :backend:api:spotlessKotlinGradle UP-TO-DATE
> Task :backend:api:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:base:spotlessJava UP-TO-DATE
> Task :branchLayout:impl:spotlessJava UP-TO-DATE
> Task :frontend:base:spotlessJavaApply UP-TO-DATE
> Task :branchLayout:impl:spotlessJavaApply UP-TO-DATE
> Task :frontend:ui:api:createCheckerFrameworkManifest UP-TO-DATE
> Task :branchLayout:api:spotlessJava UP-TO-DATE
> Task :qual:spotlessJava UP-TO-DATE
> Task :branchLayout:api:spotlessJavaApply UP-TO-DATE
> Task :qual:spotlessJavaApply UP-TO-DATE
> Task :frontend:base:spotlessKotlinGradle UP-TO-DATE
> Task :branchLayout:impl:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:base:spotlessKotlinGradleApply UP-TO-DATE
> Task :branchLayout:impl:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:base:patchPluginXml SKIPPED
> Task :frontend:base:verifyPluginConfiguration SKIPPED
> Task :branchLayout:api:spotlessKotlinGradle UP-TO-DATE
> Task :branchLayout:api:spotlessKotlinGradleApply UP-TO-DATE
> Task :qual:spotlessKotlinGradle UP-TO-DATE
> Task :qual:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:actions:createCheckerFrameworkManifest UP-TO-DATE
> Task :gitCore:jGit:createCheckerFrameworkManifest UP-TO-DATE
> Task :frontend:graph:api:createCheckerFrameworkManifest UP-TO-DATE
> Task :backend:impl:spotlessJava UP-TO-DATE
> Task :backend:impl:spotlessJavaApply UP-TO-DATE
> Task :binding:compileJava UP-TO-DATE
> Task :frontend:graph:impl:createCheckerFrameworkManifest UP-TO-DATE
> Task :backend:impl:spotlessKotlinGradle UP-TO-DATE
> Task :backend:impl:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:ui:impl:createCheckerFrameworkManifest UP-TO-DATE
> Task :qual:compileJava UP-TO-DATE
> Task :frontend:resourcebundles:spotlessJava UP-TO-DATE
> Task :frontend:ui:api:spotlessJava UP-TO-DATE
> Task :frontend:file:spotlessJava UP-TO-DATE
> Task :frontend:resourcebundles:spotlessJavaApply UP-TO-DATE
> Task :frontend:file:spotlessJavaApply UP-TO-DATE
> Task :frontend:file:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:file:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:file:patchPluginXml SKIPPED
> Task :frontend:file:verifyPluginConfiguration SKIPPED
> Task :frontend:ui:api:spotlessJavaApply UP-TO-DATE
> Task :frontend:graph:api:spotlessJava UP-TO-DATE
> Task :frontend:graph:api:spotlessJavaApply UP-TO-DATE
> Task :gitCore:jGit:spotlessJava UP-TO-DATE
> Task :frontend:ui:api:spotlessKotlinGradle UP-TO-DATE
> Task :gitCore:api:compileJava UP-TO-DATE
> Task :frontend:ui:api:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:ui:api:patchPluginXml SKIPPED
> Task :frontend:ui:api:verifyPluginConfiguration SKIPPED
> Task :gitCore:jGit:spotlessJavaApply UP-TO-DATE
> Task :frontend:graph:impl:spotlessJava UP-TO-DATE
> Task :frontend:graph:impl:spotlessJavaApply UP-TO-DATE
> Task :binding:processResources NO-SOURCE
> Task :binding:classes UP-TO-DATE
> Task :qual:processResources NO-SOURCE
> Task :qual:classes UP-TO-DATE
> Task :frontend:graph:api:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:graph:api:spotlessKotlinGradleApply UP-TO-DATE
> Task :branchLayout:api:compileJava UP-TO-DATE
> Task :gitCore:jGit:spotlessKotlinGradle UP-TO-DATE
> Task :gitCore:jGit:spotlessKotlinGradleApply UP-TO-DATE
> Task :binding:jar UP-TO-DATE
> Task :qual:jar UP-TO-DATE
> Task :frontend:graph:api:patchPluginXml SKIPPED
> Task :frontend:graph:api:verifyPluginConfiguration SKIPPED
> Task :frontend:graph:impl:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:graph:impl:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:graph:impl:patchPluginXml SKIPPED
> Task :backend:impl:processResources NO-SOURCE
> Task :frontend:graph:impl:verifyPluginConfiguration SKIPPED
> Task :branchLayout:api:processResources NO-SOURCE
> Task :branchLayout:api:classes UP-TO-DATE
> Task :frontend:file:processResources NO-SOURCE
> Task :frontend:file:setupInstrumentCode SKIPPED
> Task :gitCore:api:processResources NO-SOURCE
> Task :gitCore:api:classes UP-TO-DATE
> Task :branchLayout:api:jar UP-TO-DATE
> Task :frontend:graph:api:processResources NO-SOURCE
> Task :frontend:graph:api:setupInstrumentCode SKIPPED
> Task :gitCore:api:jar UP-TO-DATE
> Task :frontend:graph:impl:processResources NO-SOURCE
> Task :branchLayout:impl:compileJava UP-TO-DATE
> Task :frontend:graph:impl:setupInstrumentCode SKIPPED
> Task :spotlessKotlin UP-TO-DATE
> Task :frontend:ui:api:processResources NO-SOURCE
> Task :frontend:resourcebundles:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:ui:api:setupInstrumentCode SKIPPED
> Task :branchLayout:impl:processResources NO-SOURCE
> Task :spotlessKotlinApply UP-TO-DATE
> Task :backend:api:compileJava UP-TO-DATE
> Task :frontend:resourcebundles:spotlessKotlinGradleApply UP-TO-DATE
> Task :branchLayout:impl:classes UP-TO-DATE
> Task :gitCore:jGit:compileJava UP-TO-DATE
> Task :backend:api:processResources NO-SOURCE
> Task :backend:api:classes UP-TO-DATE
> Task :patchPluginXml UP-TO-DATE
> Task :branchLayout:impl:jar UP-TO-DATE
> Task :backend:api:jar UP-TO-DATE
> Task :gitCore:jGit:processResources NO-SOURCE
> Task :gitCore:jGit:classes UP-TO-DATE
> Task :frontend:base:processResources UP-TO-DATE
> Task :frontend:resourcebundles:compileJava UP-TO-DATE
> Task :frontend:resourcebundles:processResources UP-TO-DATE
> Task :gitCore:jGit:jar UP-TO-DATE
> Task :frontend:resourcebundles:classes UP-TO-DATE
> Task :frontend:resourcebundles:jar UP-TO-DATE
> Task :frontend:ui:impl:spotlessJava UP-TO-DATE
> Task :frontend:ui:impl:spotlessJavaApply UP-TO-DATE
> Task :backend:impl:compileJava UP-TO-DATE
> Task :frontend:graph:api:compileJava UP-TO-DATE
> Task :frontend:base:compileJava UP-TO-DATE
> Task :frontend:ui:api:compileJava UP-TO-DATE
> Task :backend:impl:compileAspectj NO-SOURCE
> Task :frontend:ui:impl:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:graph:api:classes UP-TO-DATE
> Task :frontend:base:classes UP-TO-DATE
> Task :frontend:base:setupInstrumentCode SKIPPED
> Task :frontend:ui:api:classes UP-TO-DATE
> Task :frontend:ui:impl:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:ui:api:instrumentCode SKIPPED
> Task :backend:impl:classes UP-TO-DATE
> Task :frontend:base:instrumentCode SKIPPED
> Task :frontend:ui:impl:patchPluginXml SKIPPED
> Task :frontend:base:postInstrumentCode SKIPPED
> Task :frontend:ui:api:postInstrumentCode SKIPPED
> Task :frontend:ui:impl:verifyPluginConfiguration SKIPPED
> Task :frontend:graph:api:instrumentCode SKIPPED
> Task :frontend:graph:api:postInstrumentCode SKIPPED
> Task :backend:impl:jar UP-TO-DATE
> Task :frontend:ui:api:jar UP-TO-DATE
> Task :frontend:base:jar UP-TO-DATE
> Task :frontend:ui:api:prepareSandbox SKIPPED
> Task :frontend:base:prepareSandbox SKIPPED
> Task :frontend:ui:impl:processResources UP-TO-DATE
> Task :frontend:ui:impl:setupInstrumentCode SKIPPED
> Task :frontend:ui:api:runIde SKIPPED
> Task :frontend:base:runIde SKIPPED
> Task :frontend:actions:spotlessJava UP-TO-DATE
> Task :frontend:actions:spotlessJavaApply UP-TO-DATE
> Task :frontend:base:classpathIndexCleanup
> Task :frontend:ui:api:classpathIndexCleanup
> Task :frontend:graph:api:jar UP-TO-DATE

> Task :verifyPluginConfiguration
[gradle-intellij-plugin :verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 221 < 223.
- The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 2022.3.1 requires sourceCompatibility=17.
See: https://jb.gg/intellij-platform-versions

> Task :frontend:graph:api:prepareSandbox SKIPPED
> Task :frontend:actions:spotlessKotlinGradle UP-TO-DATE
> Task :frontend:graph:api:runIde SKIPPED
> Task :frontend:actions:spotlessKotlinGradleApply UP-TO-DATE
> Task :frontend:graph:api:classpathIndexCleanup
> Task :frontend:graph:impl:compileJava UP-TO-DATE
> Task :frontend:graph:impl:classes UP-TO-DATE
> Task :frontend:actions:processResources NO-SOURCE
> Task :frontend:graph:impl:instrumentCode SKIPPED
> Task :createCheckerFrameworkManifest UP-TO-DATE
> Task :frontend:actions:setupInstrumentCode SKIPPED
> Task :frontend:graph:impl:postInstrumentCode SKIPPED
> Task :frontend:file:compileJava UP-TO-DATE
> Task :frontend:file:classes UP-TO-DATE
> Task :frontend:file:instrumentCode SKIPPED
> Task :frontend:file:postInstrumentCode SKIPPED
> Task :frontend:graph:impl:jar UP-TO-DATE
> Task :frontend:graph:impl:prepareSandbox SKIPPED
> Task :frontend:file:jar UP-TO-DATE
> Task :frontend:graph:impl:runIde SKIPPED
> Task :frontend:file:prepareSandbox SKIPPED
> Task :frontend:graph:impl:classpathIndexCleanup
> Task :frontend:file:runIde SKIPPED
> Task :frontend:file:classpathIndexCleanup
> Task :frontend:ui:impl:compileJava UP-TO-DATE
> Task :frontend:ui:impl:classes UP-TO-DATE
> Task :frontend:ui:impl:instrumentCode SKIPPED
> Task :frontend:ui:impl:postInstrumentCode SKIPPED
> Task :frontend:ui:impl:jar UP-TO-DATE
> Task :frontend:ui:impl:prepareSandbox SKIPPED
> Task :frontend:ui:impl:runIde SKIPPED
> Task :frontend:ui:impl:classpathIndexCleanup
> Task :frontend:actions:compileKotlin UP-TO-DATE
> Task :frontend:actions:compileJava UP-TO-DATE
> Task :frontend:actions:classes UP-TO-DATE
> Task :frontend:actions:instrumentCode SKIPPED
> Task :frontend:actions:postInstrumentCode SKIPPED
> Task :frontend:actions:jar UP-TO-DATE
> Task :frontend:actions:inspectClassesForKotlinIC UP-TO-DATE
> Task :frontend:actions:prepareSandbox SKIPPED
> Task :frontend:actions:runIde SKIPPED
> Task :frontend:actions:classpathIndexCleanup
> Task :spotlessJava UP-TO-DATE
> Task :compileKotlin NO-SOURCE
> Task :spotlessJavaApply UP-TO-DATE
> Task :spotlessKotlinGradle UP-TO-DATE
> Task :spotlessKotlinGradleApply UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :spotlessScala UP-TO-DATE
> Task :spotlessScalaApply UP-TO-DATE
> Task :compileScala NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :setupInstrumentCode
> Task :instrumentCode SKIPPED
> Task :postInstrumentCode SKIPPED
> Task :jar UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
Disconnected from the target VM, address: '127.0.0.1:63543', transport: 'socket'
> Task :prepareSandbox UP-TO-DATE
Connected to the target VM, address: 'localhost:63550', transport: 'socket'

> Task :runIde
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
2023-01-20 09:20:02,451 [    318]   WARN - #c.i.u.m.MacOSApplicationProvider - No URL bundle (CFBundleURLTypes) is defined in the main bundle.
To be able to open external links, specify protocols in the app layout section of the build file.
Example: args.urlSchemes = ["your-protocol"] will handle following links: your-protocol://open?file=file&line=line
2023-01-20 09:20:02,530 [    397]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection
2023-01-20 09:20:03,537 [   1404]   WARN - #c.i.o.a.Application - issue detected: implicit.log.directory.path
2023-01-20 09:20:19,305 [  17172]   WARN - #c.i.e.RunManager - Must be not called before project components initialized
Info  | RdCoroutineScope          | 62:DefaultDispatcher-worker-41 | RdCoroutineHost overridden 
2023-01-20 09:20:19,447 [  17314] SEVERE - #c.i.i.p.PluginManager - Argument for @NotNull parameter 'modalComponent' of com/intellij/ide/IdeEventQueue.consumeUnrelatedEvent must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'modalComponent' of com/intellij/ide/IdeEventQueue.consumeUnrelatedEvent must not be null
	at com.intellij.ide.IdeEventQueue.$$$reportNull$$$0(IdeEventQueue.java)
	at com.intellij.ide.IdeEventQueue.consumeUnrelatedEvent(IdeEventQueue.java)
	at com.intellij.openapi.progress.impl.PlatformTaskSupportKt$processEventQueueConsumingUnrelatedInputEvents$1.invokeSuspend(PlatformTaskSupport.kt:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.runBlockingModalInternal(PlatformTaskSupport.kt:76)
	at com.intellij.openapi.progress.TasksKt.runBlockingModal(tasks.kt:155)
	at com.intellij.ide.impl.ProjectUtilKt.runBlockingUnderModalProgress(ProjectUtil.kt:724)
	at com.intellij.ide.impl.ProjectUtilKt.runBlockingUnderModalProgress$default(ProjectUtil.kt:721)
	at com.intellij.ide.actions.OpenFileAction$actionPerformed$1.invoke(OpenFileAction.kt:80)
	at com.intellij.ide.actions.OpenFileAction$actionPerformed$1.invoke(OpenFileAction.kt:72)
	at com.intellij.ide.actions.OpenFileAction.actionPerformed$lambda$0(OpenFileAction.kt:72)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:137)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:102)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:80)
	at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.kt:72)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:302)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:302)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.performAnActionForComponent(WelcomeScreenActionsUtil.java:101)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil$LargeIconWithTextWrapper.lambda$new$0(WelcomeScreenActionsUtil.java:130)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-01-20 09:20:19,449 [  17316] SEVERE - #c.i.i.p.PluginManager - IntelliJ IDEA 2022.3.1  Build #IC-223.8214.52
2023-01-20 09:20:19,449 [  17316] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: Amazon.com Inc.
2023-01-20 09:20:19,449 [  17316] SEVERE - #c.i.i.p.PluginManager - OS: Mac OS X

```

</details>

## (optional) Screenshots
And the IDE looks like this
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/19799111/213649410-b77d3d24-9c11-4d95-b538-2705c44a8408.png">

**Comment by PawelLipski** [comment]
Hmmm is it related to/caused by our plugin? looks like a problem in IDEA itself 🤔

**Comment by mkondratek** [comment]
yup. that's why I am posting it as a help/question not as a bug

**Comment by mkondratek** [comment]
on the other hand I managed to create a new project with no error

**Comment by mkondratek** [comment]
heh, create new project, recreate multi root sandbox from the script, then switch to the machete sandbox - helped

**Comment by mkondratek** [comment]
works now - maybe smth went wrong on repo setup. closing
