### ISSUE TITLE
Memory leak detected: `EnhancedGraphTable` is registered in `Disposer` but wasn't disposed

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1474]
Happened on closing the project, IDE executed via `gradle runIde`.
Probably not very important, but still would be nice to fix if easy.

IIUC adding something like 

```
public EnhancedGraphTable(Project project) {
  ....
  Disposer.register(project, this);
  ....
}
```

should be enough... WDYT @mkondratek ?

TBD if other classes implementing `Disposable` are affected (like `com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox`).

```
2023-01-21 16:12:04,545 [  82358] SEVERE - #c.i.o.u.ObjectTree - Memory leak detected: 'com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable[,0,0,270x239,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=234881384,maximumSize=,minimumSize=,preferredSize=,autoCreateColumnsFromModel=false,autoResizeMode=AUTO_RESIZE_OFF,cellSelectionEnabled=false,editingColumn=-1,editingRow=-1,gridColor=javax.swing.plaf.ColorUIResource[r=79,g=81,b=82] Name: Table.gridColor,preferredViewportSize=,rowHeight=16,rowMargin=0,rowSelectionAllowed=false,selectionBackground=javax.swing.plaf.ColorUIResource[r=47,g=101,b=202] Name: Table.selectionBackground,selectionForeground=javax.swing.plaf.ColorUIResource[r=255,g=255,b=255] Name: Table.selectionForeground,showHorizontalLines=false,showVerticalLines=false]' of class com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

java.lang.RuntimeException: Memory leak detected: 'com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable[,0,0,270x239,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=234881384,maximumSize=,minimumSize=,preferredSize=,autoCreateColumnsFromModel=false,autoResizeMode=AUTO_RESIZE_OFF,cellSelectionEnabled=false,editingColumn=-1,editingRow=-1,gridColor=javax.swing.plaf.ColorUIResource[r=79,g=81,b=82] Name: Table.gridColor,preferredViewportSize=,rowHeight=16,rowMargin=0,rowSelectionAllowed=false,selectionBackground=javax.swing.plaf.ColorUIResource[r=47,g=101,b=202] Name: Table.selectionBackground,selectionForeground=javax.swing.plaf.ColorUIResource[r=255,g=255,b=255] Name: Table.selectionForeground,showHorizontalLines=false,showVerticalLines=false]' of class com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

        at com.intellij.openapi.util.ObjectNode.assertNoChildren(ObjectNode.java:44)
        at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:216)
        at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:260)
        at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:254)
        at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:197)
        at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:606)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:545)
        at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:534)
        at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:70)
        at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$Companion$setupCloseAction$1.windowClosing(WelcomeFrame.kt:115)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
        at java.desktop/java.awt.Window.processWindowEvent(Window.java:2085)
        at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
        at java.desktop/java.awt.Window.processEvent(Window.java:2044)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Throwable
        at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:25)
        at com.intellij.openapi.util.ObjectNode.findOrCreateChildNode(ObjectNode.java:141)
        at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:51)
        at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
        at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable.subscribeToGitRepositoryFilesChanges(EnhancedGraphTable.java:227)
        at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable.<init>(EnhancedGraphTable.java:167)
        at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTableFactory.create(EnhancedGraphTableFactory.java:11)
        at com.virtuslab.gitmachete.frontend.ui.services.GraphTableService.<init>(GraphTableService.java:19)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:970)
        at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:929)
        at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:733)
        at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:685)
        at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
        at com.virtuslab.gitmachete.frontend.ui.impl.root.GitMachetePanel.getGraphTable(GitMachetePanel.java:67)
        at com.virtuslab.gitmachete.frontend.ui.impl.root.GitMachetePanel.<init>(GitMachetePanel.java:44)
        at com.virtuslab.gitmachete.frontend.ui.impl.root.GitMacheteContentProvider.initContent(GitMacheteContentProvider.java:19)
        at com.intellij.openapi.vcs.changes.ui.ChangesViewContentProvider.initTabContent(ChangesViewContentProvider.java:31)
        at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager.initLazyContent(ChangesViewContentManager.kt:186)
        at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager$ContentProvidersListener.selectionChanged(ChangesViewContentManager.kt:200)
        at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
        at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
        at jdk.proxy1/jdk.proxy1.$Proxy110.selectionChanged(Unknown Source)
        at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:621)
        at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:432)
        at com.intellij.ui.content.impl.ContentManagerImpl$2.run(ContentManagerImpl.java:520)
        at com.intellij.ui.content.impl.ContentManagerImpl.lambda$setSelectedContent$4(ContentManagerImpl.java:533)
        at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
        at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
        at com.intellij.openapi.util.ActionCallback.doWhenProcessed(ActionCallback.java:129)
        at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:533)
        at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:485)
        at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:475)
        at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:470)
        at com.intellij.openapi.wm.impl.content.ContentTabLabel.selectContent(ContentTabLabel.java:152)
        at com.intellij.openapi.wm.impl.content.ContentTabLabel.handleMouseClick(ContentTabLabel.java:49)
        at com.intellij.openapi.wm.impl.content.ContentLabel$1.execute(ContentLabel.java:41)
        at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.execute(BaseButtonBehavior.java:178)
        at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.mouseReleased(BaseButtonBehavior.java:160)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
        ... 14 more
2023-01-21 16:12:04,562 [  82375] SEVERE - #c.i.o.u.ObjectTree - IntelliJ IDEA 2022.3.1  Build #IC-223.8214.52
2023-01-21 16:12:04,564 [  82377] SEVERE - #c.i.o.u.ObjectTree - JDK: 17; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation
2023-01-21 16:12:04,564 [  82377] SEVERE - #c.i.o.u.ObjectTree - OS: Mac OS X
2023-01-21 16:12:04,565 [  82378] SEVERE - #c.i.o.u.ObjectTree - Plugin to blame: Git Machete version: 3.4.0-19-SNAPSHOT+git.7be988b
```

**Comment by PawelLipski** [comment]
Whoops no

<img width="738" alt="image" src="https://user-images.githubusercontent.com/3383210/215786522-5c2d2c61-1caf-4ee7-9c4b-c125bf206fb2.png">

**Comment by PawelLipski** [comment]
It seems that registering `this` (`EnhancedGraphTable`) against a project service is the best choice (?)... probably a special dummy light service would be cleaner for this purpose than re-using any of the existing services.

**Comment by PawelLipski** [comment]
`-Didea.disposer.debug=on` in IDEA/`runIde` options might be useful

**Comment by PawelLipski** [comment]
Meh, I've checked and all three `dispose` methods that we implement (in `com.virtuslab.gitmachete.frontend.file.MacheteFileViewProviderFactory`, `com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox` and `com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable`) are invoked as expected by Disposer.

I'd assume that the above was some glitch/race condition in IntelliJ... maybe I've killed the IDE with Ctrl-C back then? 

Anyway, closing
