### ISSUE TITLE
Another race condition around slide-out/delete: `GitCoreNoSuchRevisionException: Ref 'refs/heads/develop' does not exist in this repository`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1492]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/8315/workflows/02b25868-3338-4f6a-9d67-31b678e015d6/jobs/8740/steps

Potential remedy: `com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable#disableEnqueuingUpdates` and `#enableEnqueuingUpdates` around the entire slide-out/delete "transaction"

```
 runJs: executing `project.acceptBranchDeletionOnSlideOut()`
    [intellij-stdout] opened Git Machete Branch Deletion Suggestion:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog12,1585,1013,670x133,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Git Machete Branch Deletion 
........
    [intellij-stdout] 2023-01-27 01:27:27,552 [ 332177]   WARN - com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable - Unable to create Git Machete repository
    [intellij-stdout] com.virtuslab.gitmachete.backend.api.GitMacheteException: com.virtuslab.gitcore.api.GitCoreNoSuchRevisionException: Ref 'refs/heads/develop' does not exist in this repository
    [intellij-stdout] 	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout(GitMacheteRepository.java:40)
    [intellij-stdout] 	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.updateRepositorySnapshot(GitMacheteRepositoryUpdateBackgroundable.java:108)
    [intellij-stdout] 	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.run(GitMacheteRepositoryUpdateBackgroundable.java:76)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
    [intellij-stdout] 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
    [intellij-stdout] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    [intellij-stdout] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    [intellij-stdout] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    [intellij-stdout] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    [intellij-stdout] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    [intellij-stdout] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    [intellij-stdout] 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    [intellij-stdout] 	at java.base/java.lang.Thread.run(Thread.java:833)
    [intellij-stdout] Caused by: com.virtuslab.gitcore.api.GitCoreNoSuchRevisionException: Ref 'refs/heads/develop' does not exist in this repository
    [intellij-stdout] 	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveReflogByRefFullName(GitCoreRepository.java:3)
    [intellij-stdout] 	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveAllLocalBranches$d9482c2f$1(GitCoreRepository.java:359)
    [intellij-stdout] 	at io.vavr.control.Try.of(Try.java:75)
    [intellij-stdout] 	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveAllLocalBranches$7(GitCoreRepository.java:349)
    [intellij-stdout] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    [intellij-stdout] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    [intellij-stdout] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    [intellij-stdout] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    [intellij-stdout] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    [intellij-stdout] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    [intellij-stdout] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [intellij-stdout] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    [intellij-stdout] 	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveAllLocalBranches(GitCoreRepository.java:364)
    [intellij-stdout] 	at com.virtuslab.gitmachete.backend.impl.aux.Aux.<init>(Aux.java:41)
    [intellij-stdout] 	at com.virtuslab.gitmachete.backend.impl.aux.CreateGitMacheteRepositoryAux.<init>(CreateGitMacheteRepositoryAux.java:65)
    [intellij-stdout] 	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout(GitMacheteRepository.java:37)
    [intellij-stdout] 	... 22 more
    [intellij-stdout] closed Git Machete Branch Deletion Suggestion

**Comment by PawelLipski** [comment]
Whoops I get it every single time now... lemme fix that in 3.5.0 as well

**Comment by PawelLipski** [comment]
Curiosly... `develop` is NOT a branch that is being slid out 🤔 so this is distinct from (and less obvious than) #971, which was a relatively simple race condition b/w repo refresh, deletion and slide-out

**Comment by PawelLipski** [comment]
Okay, let's leave that until 3.5.1, I need to collect more occurrences. 3.5.0 shouldn't worsen the situation when compared to 3.4.0 anyway

**Comment by PawelLipski** [comment]
Likely to be fixed with just https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1505
