### ISSUE TITLE
Attempt to rebase a branch whose fork point can't be determined shouldn't be allowed

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#151]
Likely related to #79 (FYI @mkondratek)

[git.zip](https://github.com/VirtusLab/git-machete-intellij-plugin/files/4402948/git.zip)

When trying to rebase `master` onto parent (`develop`):

```2020-03-30 15:09:41,273 [  38344]  ERROR - SelectedBranchOntoParentAction - Unable to derive rebase parameters 
com.virtuslab.gitmachete.backend.api.GitMacheteException: Cannot find fork point for branch "master"
        at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.deriveParametersForRebaseOntoParent(GitMacheteRepository.java:49)
        at com.virtuslab.gitmachete.frontend.actions.RebaseSelectedBranchOntoParentAction.lambda$deriveGitRebaseOntoParentParameters$73d76cc1$1(RebaseSelectedBranchOntoParentAction.java:91)
        at io.vavr.control.Try.of(Try.java:75)
        at com.virtuslab.gitmachete.frontend.actions.RebaseSelectedBranchOntoParentAction.deriveGitRebaseOntoParentParameters(RebaseSelectedBranchOntoParentAction.java:91)
        at com.virtuslab.gitmachete.frontend.actions.RebaseSelectedBranchOntoParentAction.actionPerformed(RebaseSelectedBranchOntoParentAction.java:62)
        at com.virtuslab.gitmachete.frontend.actions.RebaseCurrentBranchOntoParentAction.actionPerformed(RebaseCurrentBranchOntoParentAction.java:57)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:257)
        at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:194)
        at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
        at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:447)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-03-30 15:09:41,274 [  38345]  ERROR - SelectedBranchOntoParentAction - IntelliJ IDEA 2019.3  Build #IC-193.5233.102 
2020-03-30 15:09:41,274 [  38345]  ERROR - SelectedBranchOntoParentAction - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-30 15:09:41,274 [  38345]  ERROR - SelectedBranchOntoParentAction - OS: Linux 
2020-03-30 15:09:41,278 [  38349]  ERROR - SelectedBranchOntoParentAction - Plugin to blame: Git Machete version: 0.0.45-SNAPSHOT 
2020-03-30 15:09:41,279 [  38350]  ERROR - SelectedBranchOntoParentAction - Unable to get rebase parameters 
java.lang.Throwable: Unable to get rebase parameters
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
        at com.virtuslab.gitmachete.frontend.actions.RebaseSelectedBranchOntoParentAction.actionPerformed(RebaseSelectedBranchOntoParentAction.java:66)
        at com.virtuslab.gitmachete.frontend.actions.RebaseCurrentBranchOntoParentAction.actionPerformed(RebaseCurrentBranchOntoParentAction.java:57)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:257)
        at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:194)
        at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
        at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:447)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-03-30 15:09:41,279 [  38350]  ERROR - SelectedBranchOntoParentAction - IntelliJ IDEA 2019.3  Build #IC-193.5233.102 
2020-03-30 15:09:41,279 [  38350]  ERROR - SelectedBranchOntoParentAction - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-30 15:09:41,279 [  38350]  ERROR - SelectedBranchOntoParentAction - OS: Linux 
2020-03-30 15:09:41,280 [  38351]  ERROR - SelectedBranchOntoParentAction - Plugin to blame: Git Machete version: 0.0.45-SNAPSHOT 
```

**Comment by mkondratek** [comment]
Right but not for long cause after https://github.com/VirtusLab/git-machete-intellij-plugin/pull/178 it will be allowed to create a machete repository with branches missing forkpoints. 

What will happen in case of a rebase attempt in such a situation is that notification (about failed rebase caused by missing fp) in `Event Log` will appear.
