### ISSUE TITLE
java.lang.AssertionError: Can't get .git directory from repo root path file://C:/Users/gw/AppData/Local/JetBrains/PyCharm2022.3/demo/PyCharmLearningProject/git

### ISSUE THREAD

**Issue by grundew** [VirtusLab/git-machete-intellij-plugin#1630]
## Running environment
- Git Machete plugin version - 3.8.0
- IDE - PyCharm 2022.3.3
- Operating system - Windows 11 10.0

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

## IDEA - additional info
N/A

## IDEA - stack trace
```
java.lang.AssertionError: Can't get .git directory from repo root path file://C:/Users/gw/AppData/Local/JetBrains/PyCharm2022.3/demo/PyCharmLearningProject/git
	at com.virtuslab.gitmachete.frontend.vfsutils.GitVfsUtils.getMainGitDirectory(GitVfsUtils.java:6)
	at com.virtuslab.gitmachete.frontend.vfsutils.GitVfsUtils.getMainGitDirectoryPath(GitVfsUtils.java:46)
	at com.virtuslab.gitmachete.frontend.vfsutils.GitVfsUtils.getMacheteFilePath(GitVfsUtils.java:79)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable.refreshModel(EnhancedGraphTable.java:348)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable.lambda$queueRepositoryUpdateAndModelRefresh$10(EnhancedGraphTable.java:559)
	at com.virtuslab.gitmachete.frontend.ui.impl.backgroundables.GitMacheteRepositoryUpdateBackgroundable.lambda$run$0(GitMacheteRepositoryUpdateBackgroundable.java:84)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by PawelLipski** [comment]
Huh that's pretty unexpected... could you @grundew share the directory listing for `C:/Users/gw/AppData/Local/JetBrains/PyCharm2022.3/demo/PyCharmLearningProject/git`? in particular, whether `.git` folder exists?
