### ISSUE TITLE
UI tests: `java.net.BindException: Address already in use`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1685]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/9374/workflows/a6ed2e21-1e21-4456-b447-ee4b1c83b468/jobs/9807

```
> Task :uiTest_232.8660.48-EAP-SNAPSHOT
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

UITestSuite STANDARD_OUT
    Installing IntelliJ(232.8660.48-EAP-SNAPSHOT)
    Fetching https://cache-redirector.jetbrains.com/intellij-jbr/jbr-17.0.7-linux-x64-b1000.6.tar.gz into /root/.ideprobe-uitests/cache/3ef8b3eb2ee5adc0ce157d098e5a963c.gz
    Extracting jar:file:/root/.gradle/caches/modules-2/files-2.1/org.virtuslab.ideprobe/driver_2.13/0.51.0/68f810f525a94da2bf17c81b9da95d007e8ca6fb/driver_2.13-0.51.0.jar!/ideprobe_2.13-0.51.0.zip from jar into /root/.ideprobe-uitests/cache/b0c5059279608bcbd8698a9392b0b10d.zip
    Fetching https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/intellij/remoterobot/robot-server-plugin/0.11.15/robot-server-plugin-0.11.15.zip into /root/.ideprobe-uitests/cache/85cd505faee53bded778bb86be87ed21.zip
    Installed Plugin(/root/git-machete-intellij-plugin/build/distributions/git-machete-intellij-plugin-4.0.1-21+git.62df98d.zip)
    Installed Plugin(ideprobe_2.13-0.51.0)
    Installed Plugin(https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/intellij/remoterobot/robot-server-plugin/0.11.15/robot-server-plugin-0.11.15.zip)
    Display mode: Xvfb
    Starting process /root/.ideprobe-uitests/instances/intellij-instance-232.8660.48-EAP-SNAPSHOT--DQONaEL1TrKrJA05gHAVFA/bin/idea in /root/.ideprobe-uitests/workspaces/ideprobe-workspace-H5_7Wla8QMWmsZkzts4UVw/ws
    [intellij-stdout] 2023-07-18 05:58:40,996 [   1267]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Light - old: Light, new Light
    [intellij-stdout] 2023-07-18 05:58:41,437 [   1708]   WARN - java.util.prefs - Prefs file removed in background /root/.ideprobe-uitests/instances/intellij-instance-232.8660.48-EAP-SNAPSHOT--DQONaEL1TrKrJA05gHAVFA/prefs/.java/.userPrefs/prefs.xml
    [intellij-stdout] 2023-07-18 05:58:41,743 [   2014]   WARN - #c.i.u.i.IndexId - IndexId name[com.android.tools.idea.model.AndroidManifestIndex$Companion$NAME$1.NAME] should match [[A-Za-z0-9_.\-]+]. Names with unsafe characters could cause issues on some platforms. This warning likely will be escalated to an error in the following releases.
    [intellij-stdout] Probe connected to localhost/127.0.0.1:40559
    [intellij-stdout] 
    [intellij-stdout] Start Failed
    [intellij-stdout] 
    [intellij-stdout] Internal error. Please refer to https://jb.gg/ide/critical-startup-errors
    [intellij-stdout] 
    [intellij-stdout] java.net.BindException: Address already in use
    [intellij-stdout] 	at java.base/sun.nio.ch.Net.bind0(Native Method)
    [intellij-stdout] 	at java.base/sun.nio.ch.Net.bind(Net.java:555)
    [intellij-stdout] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
    [intellij-stdout] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
    [intellij-stdout] 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
    [intellij-stdout] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
    [intellij-stdout] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
    [intellij-stdout] 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
    [intellij-stdout] 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
    [intellij-stdout] 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
    [intellij-stdout] 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
    [intellij-stdout] 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
    [intellij-stdout] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    [intellij-stdout] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    [intellij-stdout] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    [intellij-stdout] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    [intellij-stdout] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    [intellij-stdout] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    [intellij-stdout] 	at java.base/java.lang.Thread.run(Thread.java:833)
    [intellij-stdout] 
    [intellij-stdout] -----
    [intellij-stdout] Your JRE: 17.0.7+7-b1000.6 amd64 (JetBrains s.r.o.)
    [intellij-stdout] /root/.ideprobe-uitests/instances/intellij-instance-232.8660.48-EAP-SNAPSHOT--DQONaEL1TrKrJA05gHAVFA/jbr
    [intellij-stdout] 
    [intellij-stdout] 2023-07-18 05:58:42,469 [   2740]   WARN - #c.i.u.i.IndexId - IndexId name[shared.index.hashes.com.android.tools.idea.model.AndroidManifestIndex$Companion$NAME$1.NAME] should match [[A-Za-z0-9_.\-]+]. Names with unsafe characters could cause issues on some platforms. This warning likely will be escalated to an error in the following releases.
    runJs: executing `ide.configure(/* enableDebugLog */ false)`
    Robot available at http://127.0.0.1:40559

UITestSuite > initializationError FAILED
    java.net.ConnectException: Failed to connect to /127.0.0.1:40559
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:59)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:35)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.com$virtuslab$gitmachete$uitest$RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$$runJs(RunningIntelliJFixtureExtension.scala:35)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$ide$.configure(RunningIntelliJFixtureExtension.scala:58)
        at com.virtuslab.gitmachete.uitest.UISuite.$anonfun$$init$$2(UISuite.scala:8)
        at com.virtuslab.gitmachete.uitest.UISuite.$anonfun$$init$$2$adapted(UISuite.scala:8)
        at org.virtuslab.ideprobe.IntelliJFixture.$anonfun$startIntelliJ$1(IntelliJFixture.scala:100)
        at org.virtuslab.ideprobe.IntelliJFixture.$anonfun$startIntelliJ$1$adapted(IntelliJFixture.scala:100)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at org.virtuslab.ideprobe.IntelliJFixture.startIntelliJ(IntelliJFixture.scala:100)
        at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.setup(ClassFixtures.scala:31)
        at org.virtuslab.ideprobe.RunningIntelliJPerSuiteBase.setup$(ClassFixtures.scala:26)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.com$virtuslab$gitmachete$uitest$UISuite$$super$setup(UITestSuite.scala:34)
        at com.virtuslab.gitmachete.uitest.UISuite.setup(UISuite.scala:18)
        at com.virtuslab.gitmachete.uitest.UISuite.setup$(UISuite.scala:18)
        at com.virtuslab.gitmachete.uitest.UITestSuite$.setup(UITestSuite.scala:34)
        at com.virtuslab.gitmachete.uitest.UITestSuite.setup(UITestSuite.scala)

        Caused by:
        java.net.ConnectException: Connection refused
            at java.base/sun.nio.ch.Net.pollConnect(Native Method)
            at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
            at java.base/java.net.Socket.connect(Socket.java:633)
            at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
            ... 37 more

2 tests completed, 1 failed, 1 skipped

> Task :uiTest_232.8660.48-EAP-SNAPSHOT FAILED
> Task :classpathIndexCleanup

FAILURE: Build failed with an exception.
```

**Comment by PawelLipski** [comment]
UI tests have been long rewritten to a different framework, this is unlikely to reoccur
