### ISSUE TITLE
`com.intellij.diagnostic.PluginException: 336 ms to call on EDT OpenMacheteTabAction#update@MainMenu`

### ISSUE THREAD

**Issue by ausarhuy** [VirtusLab/git-machete-intellij-plugin#1694]
## Running environment
- Git Machete plugin version - 4.0.0
- IDE - PyCharm 2023.2
- Operating system - Windows 10 10.0

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

## IDEA - additional info
N/A

## IDEA - stack trace
```
com.intellij.diagnostic.PluginException: 336 ms to call on EDT OpenMacheteTabAction#update@MainMenu (com.virtuslab.gitmachete.frontend.actions.vcsmenu.OpenMacheteTabAction). Revise AnAction.getActionUpdateThread property [Plugin: com.virtuslab.git-machete]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)...
	Suppressed: java.lang.Throwable: EDT-trace-at-289-ms (3/5)
		at java.base@17.0.7/java.lang.ClassLoader.defineClass2(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-237-ms (2/5)
		at java.base@17.0.7/java.lang.ClassLoader.defineClass2(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-186-ms (1/5)
		at java.base@17.0.7/java.lang.String.intern(Native Method)
		at java.base@17.0.7/java.lang.Class.getPackageName(Class.java:1084)
		at java.base@17.0.7/java.lang.ClassLoader.postDefineClass(ClassLoader.java:919)
		at java.base@17.0.7/java.lang.ClassLoader.defineClass(ClassLoader.java:1104)
		at app//com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
		at app//com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:113)
		at app//com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
		at app//com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:238)
		at app//com.intellij.util.lang.ClassPath.findClass(ClassPath.java:188)
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:326)
		at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:178)
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:151)
		at java.base@17.0.7/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		at com.virtuslab.gitmachete.frontend.actions.common.SideEffectingActionTrackingService.<init>(SideEffectingActionTrackingService.java:30)
		at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base@17.0.7/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base@17.0.7/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:976)
		at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:954)
		at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:933)
		at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService$lambda$10$lambda$8(ComponentManagerImpl.kt:740)
		at com.intellij.serviceContainer.ComponentManagerImpl$$Lambda$436/0x00000001004ba928.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$437/0x00000001004bb9f8.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$438/0x00000001004c1f78.compute(Unknown Source)
		at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
		at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:739)
		at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
		at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.getOngoingSideEffectingActions(BaseProjectDependentAction.java:43)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.update(BaseProjectDependentAction.java:66)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$985/0x0000000100ba24e8.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1179/0x0000000100cc6180.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$2230/0x000000010137cdf8.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1706/0x00000001011ed5d0.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1169/0x0000000100cbf588.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1170/0x0000000100cbf7d0.compute(Unknown Source)

**Comment by PawelLipski** [comment]
Opened https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1695, to be released soon as v4.0.1
