### ISSUE TITLE
`com.intellij.diagnostic.PluginException: 539 ms to call on EDT SyncSelectedToParentByMergeAction#update@GoToAction`

### ISSUE THREAD

**Issue by itxshakil** [VirtusLab/git-machete-intellij-plugin#1713]
## Running environment
- Git Machete plugin version - 4.0.1
- IDE - PhpStorm 2023.2
- Operating system - Windows 10 10.0

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

## IDEA - additional info
N/A

## IDEA - stack trace
```
com.intellij.diagnostic.PluginException: 539 ms to call on EDT SyncSelectedToParentByMergeAction#update@GoToAction (com.virtuslab.gitmachete.frontend.actions.contextmenu.SyncSelectedToParentByMergeAction). Revise AnAction.getActionUpdateThread property [Plugin: com.virtuslab.git-machete]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)...
	Suppressed: java.lang.Throwable: EDT-trace-at-322-ms (5/5)
		at java.base@17.0.7/java.lang.ClassLoader.defineClass2(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-259-ms (4/5)
		at java.base@17.0.7/java.util.zip.Inflater.inflateBufferBuffer(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-203-ms (3/5)
		at java.base@17.0.7/java.util.zip.Inflater.inflateBufferBuffer(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-152-ms (2/5)
		at java.base@17.0.7/java.util.zip.Inflater.inflateBufferBuffer(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-100-ms (1/5)
		at com.virtuslab.gitmachete.frontend.actions.common.SideEffectingActionTrackingService.getOngoingActions(SideEffectingActionTrackingService.java:39)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.getOngoingSideEffectingActions(BaseProjectDependentAction.java:49)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.update(BaseProjectDependentAction.java:72)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1142/0x0000000100daf180.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1254/0x0000000100eb6c60.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1895/0x00000001014268d0.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1857/0x00000001013f3df8.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1248/0x0000000100eb3d60.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1249/0x0000000100eb7220.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:231)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1894/0x0000000101426688.invoke(Unknown Source)
		at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:229)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1892/0x00000001014261f8.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1893/0x0000000101426440.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:47)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1260/0x0000000100eb9fe0.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
		at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
		at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
		at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
		at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
		at com.intellij.openapi.application.impl.FlushQueue$$Lambda$536/0x00000001005f5580.run(Unknown Source)
		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
		at java.base@17.0.7/java.security.AccessController.executePrivileged(AccessController.java:776)
		at java.base@17.0.7/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base@17.0.7/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
		at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)

**Comment by PawelLipski** [comment]
To be fixed soon with v4.0.2
