### ISSUE TITLE
`com.intellij.diagnostic.PluginException: 490 ms to call on EDT FetchAllRemotesAction#update@GoToAction`

### ISSUE THREAD

**Issue by itxshakil** [VirtusLab/git-machete-intellij-plugin#1717]
## Running environment
- Git Machete plugin version - 4.0.1
- IDE - PhpStorm 2023.2
- Operating system - Windows 10 10.0

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

## IDEA - additional info
N/A

## IDEA - stack trace
```
com.intellij.diagnostic.PluginException: 490 ms to call on EDT FetchAllRemotesAction#update@GoToAction (com.virtuslab.gitmachete.frontend.actions.toolbar.FetchAllRemotesAction). Revise AnAction.getActionUpdateThread property [Plugin: com.virtuslab.git-machete]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)...
	Suppressed: java.lang.Throwable: EDT-trace-at-357-ms (5/5)
		at java.base@17.0.7/java.util.zip.Inflater.inflateBufferBuffer(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-295-ms (4/5)
		at io.vavr.collection.List$Cons.<init>(List.java:1814)...
	Suppressed: java.lang.Throwable: EDT-trace-at-234-ms (3/5)
		at java.base@17.0.7/java.security.AccessController.getStackAccessControlContext(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-170-ms (2/5)
		at com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox.<init>(GitRepositoryComboBox.java:41)...
	Suppressed: java.lang.Throwable: EDT-trace-at-107-ms (1/5)
		at java.base@17.0.7/java.lang.StringLatin1.hashCode(StringLatin1.java:196)
		at java.base@17.0.7/java.lang.String.hashCode(String.java:2340)
		at java.base@17.0.7/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1694)
		at kr.pe.kwonnam.slf4jlambda.AbstractLambdaLoggerFactory.getLogger(AbstractLambdaLoggerFactory.java:26)
		at kr.pe.kwonnam.slf4jlambda.LambdaLoggerFactory.getLogger(LambdaLoggerFactory.java:17)
		at kr.pe.kwonnam.slf4jlambda.LambdaLoggerFactory.getLogger(LambdaLoggerFactory.java:21)
		at com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox.<clinit>(GitRepositoryComboBox.java:29)
		at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base@17.0.7/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base@17.0.7/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:95)
		at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
		at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
		at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
		at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
		at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
		at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
		at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
		at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.getSelectedGitRepository(BaseProjectDependentAction.java:113)
		at com.virtuslab.gitmachete.frontend.actions.toolbar.FetchAllRemotesAction.onUpdate(FetchAllRemotesAction.java:47)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.update(BaseProjectDependentAction.java:84)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1068/0x0000000100cfec50.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1203/0x0000000100ddcd58.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1828/0x00000001011ef528.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1831/0x00000001011f7248.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1197/0x0000000100dd7780.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1198/0x0000000100dd7be8.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:231)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1827/0x00000001011eec38.invoke(Unknown Source)
		at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)

**Comment by PawelLipski** [comment]
Huh okay lemme still address that on a one-by-one basis... but slowly this asks for a more systematic solution ☹️
