### ISSUE TITLE
`com.intellij.diagnostic.PluginException: 389 ms to call on EDT FetchAllRemotesAction#update@GoToAction`

### ISSUE THREAD

**Issue by itxshakil** [VirtusLab/git-machete-intellij-plugin#1719]
## Running environment
- Git Machete plugin version - 4.0.2
- IDE - PhpStorm 2023.2
- Operating system - Windows 10 10.0

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

## IDEA - additional info
N/A

## IDEA - stack trace
```
com.intellij.diagnostic.PluginException: 389 ms to call on EDT FetchAllRemotesAction#update@GoToAction (com.virtuslab.gitmachete.frontend.actions.toolbar.FetchAllRemotesAction). Revise AnAction.getActionUpdateThread property [Plugin: com.virtuslab.git-machete]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)...
	Suppressed: java.lang.Throwable: EDT-trace-at-356-ms (5/5)
		at java.base@17.0.7/java.lang.ClassLoader.defineClass2(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-294-ms (4/5)
		at com.virtuslab.gitmachete.frontend.ui.impl.gitrepositoryselection.GitRepositoryComboBox$$Lambda$13346/0x000000010433a6f8.<init>(Unknown Source)...
	Suppressed: java.lang.Throwable: EDT-trace-at-231-ms (3/5)
		at java.base@17.0.7/java.util.zip.Inflater.inflateBufferBuffer(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-169-ms (2/5)
		at java.base@17.0.7/java.util.zip.Inflater.inflateBufferBuffer(Native Method)...
	Suppressed: java.lang.Throwable: EDT-trace-at-106-ms (1/5)
		at java.base@17.0.7/java.lang.Class.getDeclaredConstructors0(Native Method)
		at java.base@17.0.7/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
		at java.base@17.0.7/java.lang.Class.getDeclaredConstructors(Class.java:2555)
		at com.intellij.serviceContainer.ConstructorInjectionKt.getSortedMatchingConstructors(constructorInjection.kt:236)
		at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:40)
		at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
		at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
		at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
		at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
		at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
		at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
		at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
		at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.getSelectedGitRepository(BaseProjectDependentAction.java:116)
		at com.virtuslab.gitmachete.frontend.actions.toolbar.FetchAllRemotesAction.onUpdate(FetchAllRemotesAction.java:47)
		at com.virtuslab.gitmachete.frontend.actions.base.BaseProjectDependentAction.update(BaseProjectDependentAction.java:87)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1176/0x0000000100dabce8.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1291/0x0000000100ea7200.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1847/0x00000001013d61d0.compute(Unknown Source)
		at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
		at com.intellij.openapi.progress.ProgressManager$$Lambda$1848/0x00000001013d6440.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1285/0x0000000100ea5970.run(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
		at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1286/0x0000000100ea5dd8.compute(Unknown Source)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
		at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:231)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1846/0x00000001013d5f88.invoke(Unknown Source)
		at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:229)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$$Lambda$1844/0x00000001013d5af8.get(Unknown Source)
		at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
		at io.opentelemetry.context.Context$$Lambda$1845/0x00000001013d5d40.get(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:47)
		at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor$$Lambda$1297/0x0000000100ead7a0.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)

**Comment by PawelLipski** [comment]
Huh let's take more drastic steps...
