### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'displayId' of git4idea/util/LocalChangesWouldBeOverwrittenHelper.showErrorNotification must not be null

### ISSUE THREAD

**Issue by fan-tom** [VirtusLab/git-machete-intellij-plugin#1850]
## Running environment
- Git Machete plugin version - 4.2.0
- IDE - IntelliJ IDEA 2024.1.1 RC
- Operating system - Mac OS X 14.4.1

## Bug description
**Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour**.

## (optional) Screenshots
If applicable, add screenshots (or screen recordings, see [Peek](https://github.com/phw/peek#peek---an-animated-gif-recorder) on Linux)
to help explain your problem.

## IDEA - additional info
N/A

## IDEA - stack trace
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'displayId' of git4idea/util/LocalChangesWouldBeOverwrittenHelper.showErrorNotification must not be null
	at git4idea.util.LocalChangesWouldBeOverwrittenHelper.$$$reportNull$$$0(LocalChangesWouldBeOverwrittenHelper.java)
	at git4idea.util.LocalChangesWouldBeOverwrittenHelper.showErrorNotification(LocalChangesWouldBeOverwrittenHelper.java)
	at com.virtuslab.gitmachete.frontend.actions.backgroundables.GitCommandUpdatingCurrentBranchBackgroundable.handleResult(GitCommandUpdatingCurrentBranchBackgroundable.java:170)
	at com.virtuslab.gitmachete.frontend.actions.backgroundables.GitCommandUpdatingCurrentBranchBackgroundable.doRun(GitCommandUpdatingCurrentBranchBackgroundable.java:97)
	at com.virtuslab.gitmachete.frontend.actions.backgroundables.SideEffectingBackgroundable.run(SideEffectingBackgroundable.java:29)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by PawelLipski** [comment]
Fixed at #1851, to be released soon as v4.2.1
