### ISSUE TITLE
IDE Fatal Error: Unable to create Git Machete repository 

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#252]
It came out during investigation on #190. The circumstances are the same, so:
- quickly switch between VCS roots in combobox (arrow keys give you +10 to speed)

![image](https://user-images.githubusercontent.com/19799111/80918326-9ee0cc80-8d64-11ea-855a-c2c445cb4ed0.png)

<details>
<summary>
stack trace
</summary>
GitMacheteGraphTableManager#updateRepository: Unable to create Git Machete repository

com.virtuslab.gitmachete.backend.api.GitMacheteException: com.virtuslab.gitcore.api.GitCoreNoSuchBranchException: Local branch 'forbid-ownership-link' does not exist in this repository
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.lambda$createGitMacheteNonRootBranch$9(GitMacheteRepositoryFactory.java:101)
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.createGitMacheteNonRootBranch(GitMacheteRepositoryFactory.java:101)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.lambda$deriveDownstreamBranches$7c95b0d1$1(GitMacheteRepositoryFactory.java:193)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.lambda$deriveDownstreamBranches$19(GitMacheteRepositoryFactory.java:192)
	at io.vavr.collection.List.map(List.java:1038)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.deriveDownstreamBranches(GitMacheteRepositoryFactory.java:192)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.createGitMacheteRootBranch(GitMacheteRepositoryFactory.java:90)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.lambda$create$779f444d$1(GitMacheteRepositoryFactory.java:63)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.lambda$create$2(GitMacheteRepositoryFactory.java:63)
	at io.vavr.collection.List.map(List.java:1038)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.create(GitMacheteRepositoryFactory.java:63)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteGraphTableManager.updateRepository(GitMacheteGraphTableManager.java:221)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteGraphTableManager$1.run(GitMacheteGraphTableManager.java:191)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.virtuslab.gitcore.api.GitCoreNoSuchBranchException: Local branch 'forbid-ownership-link' does not exist in this repository
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.getLocalBranch(GitCoreRepository.java:74)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.getLocalBranch(GitCoreRepository.java:34)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.lambda$createGitMacheteNonRootBranch$8364ae9$1(GitMacheteRepositoryFactory.java:100)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory.createGitMacheteNonRootBranch(GitMacheteRepositoryFactory.java:100)
	... 26 more
</details>

**Comment by mkondratek** [comment]
**Observation:** 
The branch layout provided to `com.virtuslab.gitmachete.backend.impl.GitMacheteRepositoryFactory#create` does not represent the repository that is under construction.

**Comment by mkondratek** [comment]
It will be resolved together with the "origin issue" on #251
