### ISSUE TITLE
Plugin visibility on Git VCS but no VCS root

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#255]
The comment on `VcsRootComboBox#updateRepositories` says:
> GitUtil.getRepositories(project) should never return empty list because it means there's no git repository in an opened project, so Git Machete plugin shouldn't even be loaded in the first place (as ensured by GitMacheteVisibilityPredicate)
    
**That is not true.** 

Visibility predicate guarantees that Git is an active Vcs but it is not equivalent to the fact that at least one repository exists. 

***

We can:
- make visibility predicate depend on repository presence as well
- provide a proper description to the user why the table is empty (I assume that this is preferred option)

***

Additional action:
If the second option fo the above will be chosen then one step further shall be considered. Instead of hiding the plugin in case of inactive Git VCS we could provide some info too.

**Comment by mkondratek** [comment]
**Bug description**

Occurs on #254 

**Steps to reproduce:**
1. Having Git Vcs single root repo
2. Remove repo (from the outside world)

**Expected:** 
undefined

**Actual:**
graph table does not change (previous repo UI left)

**Comment by mkondratek** [comment]
Presently the scenario from above results with an error

<details>
  <summary>stacktrace</summary>
java.lang.AssertionError: Can't get .git directory from repo root path file:///home/mkondratek/IdeaProjects/git-machete-intellij-plugin
	at com.virtuslab.gitmachete.frontend.vfsutils.GitVfsUtils.getGitDirectory(GitVfsUtils.java:7)
	at com.virtuslab.gitmachete.frontend.vfsutils.GitVfsUtils.getMacheteFile(GitVfsUtils.java:40)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable.lambda$queueRepositoryUpdateAndModelRefresh$5(EnhancedGraphTable.java:322)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:276)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.EnhancedGraphTable.queueRepositoryUpdateAndModelRefresh(EnhancedGraphTable.java:300)
	at com.virtuslab.gitmachete.frontend.ui.api.table.BaseEnhancedGraphTable.queueRepositoryUpdateAndModelRefresh(BaseEnhancedGraphTable.java:37)
	at com.virtuslab.gitmachete.frontend.actions.toolbar.RefreshStatusAction.actionPerformed(RefreshStatusAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:439)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</details>

**Comment by mkondratek** [comment]
It's been a while... there were no updates on this one, no reappearance reports.

I ve just run the above reproduction scenario - deleting a repo from the outside world simply makes the plugin tab invisible (based on visibility predicate). No internal ide errors. 

I think we can close it (@PawelLipski ?).

**Comment by PawelLipski** [comment]
Gr8 🎉 the best bug, got resolved itself automagically
