### ISSUE TITLE
NPE in deriveMergeBase

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#670]
![image](https://user-images.githubusercontent.com/3383210/103176428-c9dadc00-4871-11eb-9d79-0bd4ccc986ec.png)

Happens on the repository: [ide-probe.zip](https://github.com/VirtusLab/git-machete-intellij-plugin/files/5744873/ide-probe.zip)

Plugin version 0.8.2-15-SNAPSHOT+git.10ecbaf (built from PR #666, but not likely to be PR-specific)

```
2020-12-27 18:26:17,835 [360923081]  ERROR -         gitmachete.frontend.ui - GitMacheteRepositoryUpdateBackgroundable#handleUpdateRepositoryException: Unable to create Git Machete repository
com.virtuslab.gitmachete.backend.api.GitMacheteException: com.virtuslab.gitcore.api.GitCoreException: java.lang.NullPointerException
	at com.virtuslab.gitmachete.backend.api.GitMacheteException.getOrWrap(GitMacheteException.java:21)
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createSnapshot(GitMacheteRepository.java:313)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout(GitMacheteRepository.java:79)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.lambda$updateRepositorySnapshot$4b6e116c$1(GitMacheteRepositoryUpdateBackgroundable.java:89)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.updateRepositorySnapshot(GitMacheteRepositoryUpdateBackgroundable.java:87)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.run(GitMacheteRepositoryUpdateBackgroundable.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.virtuslab.gitcore.api.GitCoreException: java.lang.NullPointerException
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.withRevWalk(GitCoreRepository.java:89)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveMergeBase(GitCoreRepository.java:320)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveMergeBaseIfNeeded(GitCoreRepository.java:361)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.isAncestor(GitCoreRepository.java:376)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.deriveParentAwareForkPoint(GitMacheteRepository.java:463)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createGitMacheteNonRootBranch(GitMacheteRepository.java:405)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$deriveChildBranches$2bab6c10$1(GitMacheteRepository.java:593)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$deriveChildBranches$23(GitMacheteRepository.java:592)
	at io.vavr.collection.List.map(List.java:1042)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.deriveChildBranches(GitMacheteRepository.java:592)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createGitMacheteRootBranch(GitMacheteRepository.java:379)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$createSnapshot$4cd04c2b$1(GitMacheteRepository.java:312)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.lambda$createSnapshot$0(GitMacheteRepository.java:312)
	at io.vavr.collection.List.map(List.java:1042)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.createSnapshot(GitMacheteRepository.java:312)
	... 22 more
Caused by: java.lang.NullPointerException
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveMergeBase$20(GitCoreRepository.java:337)
	at com.virtuslab.logger.EnhancedLambdaLogger.lambda$debug$5(EnhancedLambdaLogger.java:101)
	at kr.pe.kwonnam.slf4jlambda.defaultlogger.LambdaLoggerLocationAwareImpl.doLog(LambdaLoggerLocationAwareImpl.java:50)
	at kr.pe.kwonnam.slf4jlambda.LambdaLogger.debug(LambdaLogger.java:352)
	at com.virtuslab.logger.EnhancedLambdaLogger.debug(EnhancedLambdaLogger.java:101)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveMergeBase$2ef846b4$1(GitCoreRepository.java:336)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.withRevWalk(GitCoreRepository.java:87)
	... 38 more

```

**Comment by PawelLipski** [comment]
Whoops Checker Framework didn't capture that `mergeBase` passed to lambda here:

![image](https://user-images.githubusercontent.com/3383210/103177046-1379f580-4877-11eb-843f-50dcac813e6b.png)

can be null 🤔
