### ISSUE TITLE
NPE when a pull isn't possible b/c non-FF or remote branch no longer exists

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#676]
**Repro**: Pull a branch whose remote tracking branch has been removed, or diverged, so that FF pull doesn't succeed.

**Expected**: an error notification

**Actual**: no error notification, NPE is thrown

```
java.lang.NullPointerException
	at com.intellij.openapi.vcs.VcsNotifier.stringifyErrors(VcsNotifier.java:485)
	at com.intellij.openapi.vcs.VcsNotifier.buildNotificationMessage(VcsNotifier.java:459)
	at com.intellij.openapi.vcs.VcsNotifier.notifyError(VcsNotifier.java:109)
	at git4idea.util.GitUIUtil.notifyError(GitUIUtil.java:59)
	at com.virtuslab.gitmachete.frontend.actions.backgroundables.GitCommandUpdatingCurrentBranchBackgroundable.handleResult(GitCommandUpdatingCurrentBranchBackgroundable.java:179)
	at com.virtuslab.gitmachete.frontend.actions.backgroundables.GitCommandUpdatingCurrentBranchBackgroundable.run(GitCommandUpdatingCurrentBranchBackgroundable.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by PawelLipski** [comment]
Ok, opened https://youtrack.jetbrains.com/issue/IDEA-258711; I'll switch away from this deprecated method directly to VcsNotifier anyway
