### ISSUE TITLE
Actions still get stalled on `FileContentUtilCore#reparseFiles`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#679]
Similar to #669, despite the fix pushed as #675... this time lemme consider opening an issue against IntelliJ IDEA since it's not really expected anymore :// => opened as [IDEA-259042](https://youtrack.jetbrains.com/issue/IDEA-259042)

Version: `0.8.2-28-SNAPSHOT+git.c6412b4`

Thread stack dump \#1:

```
"AWT-EventQueue-0" #26 prio=6 os_prio=0 cpu=1105878.95ms elapsed=156459.83s tid=0x00007f87100f7000 nid=0x3da2cd runnable  [0x00007f8705e40000]
   java.lang.Thread.State: RUNNABLE
	at java.util.Collections$UnmodifiableCollection$1.<init>(java.base@11.0.9/Collections.java:1044)
	at java.util.Collections$UnmodifiableCollection.iterator(java.base@11.0.9/Collections.java:1043)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.collectEvents(VirtualFilePointerManagerImpl.java:475)
	- locked <0x00000005b9048318> (a com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.prepareChange(VirtualFilePointerManagerImpl.java:581)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl$MyAsyncFileListener.prepareChange(VirtualFilePointerManagerImpl.java:75)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.lambda$runAsyncListeners$0(AsyncEventSupport.java:79)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport$$Lambda$4911/0x0000000802984440.run(Unknown Source)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.ReadAction$$Lambda$2281/0x0000000801a83840.compute(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.runAsyncListeners(AsyncEventSupport.java:79)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport$1.before(AsyncEventSupport.java:42)
	at jdk.internal.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.9/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.9/Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:652)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:401)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:383)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:189)
	at com.sun.proxy.$Proxy142.before(Unknown Source)
	at com.intellij.util.FileContentUtilCore.lambda$reparseFiles$0(FileContentUtilCore.java:49)
	at com.intellij.util.FileContentUtilCore$$Lambda$15454/0x000000080571b040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.intellij.util.FileContentUtilCore.reparseFiles(FileContentUtilCore.java:38)
	at com.intellij.util.FileContentUtilCore.reparseFiles(FileContentUtilCore.java:29)
	at com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider.lambda$subscribeToGitRepositoryChanges$0(MacheteFileViewProviderFactory.java:49)
	at com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider$$Lambda$15453/0x000000080571bc40.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$320/0x0000000800539c40.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.9/InvocationEvent.java:313)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.9/EventQueue.java:776)
	at java.awt.EventQueue$4.run(java.desktop@11.0.9/EventQueue.java:727)
	at java.awt.EventQueue$4.run(java.desktop@11.0.9/EventQueue.java:721)
	at java.security.AccessController.doPrivileged(java.base@11.0.9/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.9/ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.9/EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.ide.IdeEventQueue$$Lambda$519/0x000000080071dc40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.ide.IdeEventQueue$$Lambda$518/0x000000080071ec40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.9/EventDispatchThread.java:203)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.9/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.9/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.9/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.9/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.9/EventDispatchThread.java:90)
```

Thread stack dump \#2:

```
"AWT-EventQueue-0" #26 prio=6 os_prio=0 cpu=1122672.98ms elapsed=156477.02s tid=0x00007f87100f7000 nid=0x3da2cd runnable  [0x00007f8705e40000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.clear(java.base@11.0.9/ConcurrentHashMap.java:1213)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollectorCache.clear(ImplicitCollectorCache.scala:75)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.clearCaches(ScalaPsiManager.scala:317)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.clearOnChange(ScalaPsiManager.scala:323)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.clearOnTopLevelChange(ScalaPsiManager.scala:329)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.clearOnNonScalaChange(ScalaPsiManager.scala:387)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.$anonfun$psiChangeListener$2(ScalaPsiManager.scala:339)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$$Lambda$1608/0x0000000801571c40.apply$mcV$sp(Unknown Source)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiChangeListener$ScalaPsiChangeListenerImpl.propertyChanged(ScalaPsiChangeListener.scala:56)
	at com.intellij.psi.impl.PsiManagerImpl.notifyPsiTreeChangeListener(PsiManagerImpl.java:410)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:349)
	at com.intellij.psi.impl.PsiManagerImpl.propertyChanged(PsiManagerImpl.java:312)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.forceReload(FileManagerImpl.java:133)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.propertyChanged(PsiVFSListener.java:359)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fireForGrouped(PsiVFSListener.java:756)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$$Lambda$4948/0x00000008029af440.accept(Unknown Source)
	at one.util.streamex.CollapseSpliterator.accept(CollapseSpliterator.java:150)
	at one.util.streamex.CollapseSpliterator.forEachRemaining(CollapseSpliterator.java:140)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:306)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.groupAndFire(PsiVFSListener.java:729)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.after(PsiVFSListener.java:718)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$1.after(PsiVFSListener.java:152)
	at jdk.internal.reflect.GeneratedMethodAccessor218.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.9/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.9/Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:652)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:401)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:383)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:189)
	at com.sun.proxy.$Proxy142.after(Unknown Source)
	at com.intellij.util.FileContentUtilCore.lambda$reparseFiles$0(FileContentUtilCore.java:50)
	at com.intellij.util.FileContentUtilCore$$Lambda$15454/0x000000080571b040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.intellij.util.FileContentUtilCore.reparseFiles(FileContentUtilCore.java:38)
	at com.intellij.util.FileContentUtilCore.reparseFiles(FileContentUtilCore.java:29)
	at com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider.lambda$subscribeToGitRepositoryChanges$0(MacheteFileViewProviderFactory.java:49)
	at com.virtuslab.gitmachete.frontend.file.MacheteFileViewProvider$$Lambda$15453/0x000000080571bc40.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$320/0x0000000800539c40.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.9/InvocationEvent.java:313)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.9/EventQueue.java:776)
	at java.awt.EventQueue$4.run(java.desktop@11.0.9/EventQueue.java:727)
	at java.awt.EventQueue$4.run(java.desktop@11.0.9/EventQueue.java:721)
	at java.security.AccessController.doPrivileged(java.base@11.0.9/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.9/ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.9/EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.ide.IdeEventQueue$$Lambda$519/0x000000080071dc40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.ide.IdeEventQueue$$Lambda$518/0x000000080071ec40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.9/EventDispatchThread.java:203)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.9/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.9/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.9/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.9/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.9/EventDispatchThread.java:90)
```

\#2 actually clearly caught IDEA red-handed while parsing Scala files (rather than machete file)

**Comment by PawelLipski** [comment]
Wasn't relevant until v3.2.0... but now would be useful for https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1281
