### ISSUE TITLE
Assertion failed beneath `setDeleteLocalBranchOnSlideOutGitConfigValue`

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#697]
plugin version: `0.8.3-13+git.04322fe`

most likely introduced by #633 and related to calling something (write operation) on the wrong thread

<details>
<summary>Stacktrace</summary>

java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:195)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:204)
	at org.jetbrains.ide.BuiltInServerManagerImpl.waitForStart(BuiltInServerManagerImpl.kt:109)
	at org.jetbrains.git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort(GitXmlRpcHandlerService.java:71)
	at git4idea.commands.GitHandlerAuthenticationManager.prepareHttpAuth(GitHandlerAuthenticationManager.java:93)
	at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:60)
	at git4idea.GitUtil.tryRunOrClose(GitUtil.java:1041)
	at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:59)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:171)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:73)
	at git4idea.config.GitConfigUtil.setValue(GitConfigUtil.java:144)
	at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.setDeleteLocalBranchOnSlideOutGitConfigValue(BaseSlideOutBranchAction.java:235)
	at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.suggestBranchDeletion(BaseSlideOutBranchAction.java:159)
	at com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.lambda$deleteBranchIfRequired$3(BaseSlideOutBranchAction.java:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

</details>

**Comment by PawelLipski** [comment]
Wowow why on earth would it call sth like `org.jetbrains.git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort` just for setting a git config? 😯

**Comment by PawelLipski** [comment]
Whoops... I see the problem, a `@NotUIThreadSafe` method (`BaseSlideOutBranchAction#setDeleteLocalBranchOnSlideOutGitConfigValue`) has been called from a `@UIEffect` method (`BaseSlideOutBranchAction#suggestBranchDeletion`)... we still can't verify that using with CheckerFramework (since it can't check calls in this direction &mdash; CF only prevents from calling `@UIEffect` methods from non-`@UIEffect` ones)

**Comment by PawelLipski** [comment]
CF won't help... but lemme see if this can be worked around with ArchUnit xD

![image](https://user-images.githubusercontent.com/3383210/106298078-b8f7fe80-6253-11eb-8cc8-227d5f5129ff.png)
