### ISSUE TITLE
Fatal error from GitPushDialog

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#768]
## Bug description
I do not recall the specific conditions.

### Running environment
 - Git Machete plugin version: 1.0.1

IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: com.andrey4623.rainbowcsv (2.0), net.seesharpsoft.intellij.plugins.csv (2.17.1), org.intellij.plugins.hcl (0.7.13), com.virtuslab.git-machete (1.0.1), PythonCore (212.5080.74), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), org.intellij.scala (2021.2.17), com.github.tomasmilata.intelliroutes (2021.2.0), com.chesterccw.excelreader (2.0.0)
Kotlin: 212-1.5.30-release-409-IJ4638.7

### Logs

<details>
<summary>Logs</summary>
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create org.jetbrains.plugins.github.util.GithubProjectSettings because container is already disposed (container=Project(name=data-pipelines, containerState=DISPOSE_COMPLETED, componentStore=/Users/mkondratek/IdeaProjects/data-pipelines) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:43)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:612)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at org.jetbrains.plugins.github.util.GithubProtectedBranchProvider.doGetProtectedBranchPatterns(GithubProjectSettings.kt:42)
	at git4idea.config.GitProtectedBranchProvider$Companion.getProtectedBranchPatterns(GitProtectedBranchProvider.kt:13)
	at git4idea.config.GitProtectedBranchProvider.getProtectedBranchPatterns(GitProtectedBranchProvider.kt)
	at git4idea.config.GitSharedSettings.getAdditionalProhibitedPatterns(GitSharedSettings.java:79)
	at git4idea.config.GitSharedSettings.isBranchProtected(GitSharedSettings.java:70)
	at git4idea.push.GitPushSupport.isForcePushAllowed(GitPushSupport.java:144)
	at git4idea.push.GitPushSupport.isForcePushAllowed(GitPushSupport.java:25)
	at com.intellij.dvcs.push.ui.PushUtils.getProhibitedTarget(PushUtils.kt:14)
	at com.intellij.dvcs.push.ui.ForcePushAction.isEnabled(ForcePushAction.kt:21)
	at com.intellij.dvcs.push.ui.VcsPushDialog$ActionWrapper.update(VcsPushDialog.java:406)
	at com.intellij.dvcs.push.ui.VcsPushDialog.updateOkActions(VcsPushDialog.java:333)
	at com.virtuslab.gitmachete.frontend.actions.dialogs.GitPushDialog$MyVcsPushDialog.updateOkActions(GitPushDialog.java:101)
	at com.intellij.dvcs.push.ui.VcsPushDialog.doValidate(VcsPushDialog.java:189)
	at com.intellij.openapi.ui.DialogWrapper.doValidateAll(DialogWrapper.java:376)
	at com.intellij.openapi.ui.DialogWrapper.lambda$initValidation$9(DialogWrapper.java:1445)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:391)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</details>

**Comment by PawelLipski** [comment]
That error is reported many times across different IntelliJ platform projects... this issue seems to to provide a bit more insight than most others: https://jira.sonarsource.com/browse/SLI-418

**Comment by PawelLipski** [comment]
Anyway, I don't think there's a better solution here than just add `if (!project.isDisposed()) ...` checks wherever we observe this error... which I'm gonna do now for `com.virtuslab.gitmachete.frontend.actions.dialogs.GitPushDialog.MyVcsPushDialog#updateOkActions`

**Comment by PawelLipski** [comment]
Resolved with #769
