### ISSUE TITLE
`discoverBranchLayout` UI test failing: spurious `component must be showing on the screen to determine its location`

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#968]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/5492/workflows/c1767cdd-515c-4e8c-ade6-fc2559b05567/jobs/5793

```
com.virtuslab.gitmachete.uitest.UITestSuite > discoverBranchLayout STANDARD_OUT
    request[projects/all]: ()
    response: []
    request[project/open]: "/tmp/machete-tests-9998989093776029449/machete-sandbox-worktree"
    [intellij-stdout] opened com.intellij.openapi.wm.impl.IdeFrameImpl
    [intellij-stdout] closed Welcome to IntelliJ IDEA (ROOT)
    [intellij-stdout] 
    response: ()
    Waiting for 1 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0]
    [intellij-stdout] opened javax.swing.JWindow
    Waiting for 1 background task(s)... [Updating indexes 634964752: running=true; canceled=false; task=com.intellij.openapi.project.DumbServiceImpl$5@72edb4b5]
    Waiting for 3 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0, com.intellij.util.indexing.PoweredProgressIndicator@718ea54a, Updating indexes 634964752: running=true; canceled=false; task=com.intellij.openapi.project.DumbServiceImpl$5@72edb4b5]
    Waiting for 3 background task(s)... [com.intellij.openapi.progress.impl.NonCancelableIndicator$1@0, com.intellij.util.indexing.PoweredProgressIndicator@718ea54a, Updating indexes 634964752: running=true; canceled=false; task=com.intellij.openapi.project.DumbServiceImpl$5@72edb4b5]
    runJs: executing `project.configure()`
    runJs: executed `project.configure()`
    request[projects/all]: ()
    response: [{"name":"machete-sandbox-worktree"}]
    runJs: executing `project.openGitMacheteTab()`
    runJs: executed `project.openGitMacheteTab()`
    runJs: executing `project.acceptSuggestedBranchLayout()`
    [intellij-stderr] 2022-07-05 13:05:44,257 [  33990]   WARN - ernallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree 
    [intellij-stdout] closed javax.swing.JWindow
    [intellij-stdout] opened Git Machete: Rediscover Suggestion:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,250,469,780x86,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Git Machete: Rediscover Suggestion,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,780x86,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]
    [intellij-stdout] closed Git Machete: Rediscover Suggestion
    runJs: executed `project.acceptSuggestedBranchLayout()`
    Waiting for 1 background task(s)... [Updating Git Machete status 924285945: running=true; canceled=false; task=com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable@33881e5e]
    [intellij-stderr] 2022-07-05 13:05:47,455 [  37188]   WARN - ernallyAddedFilesProcessorImpl - Cannot find project config directory for non-default and non-directory based project machete-sandbox-worktree 
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `8`
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `8`
    runJs: executing `project.toolbar.discoverBranchLayout()`
    runJs: executed `project.toolbar.discoverBranchLayout()`
    [intellij-stdout] opened Discovered branch layout:[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog1,428,360,424x304,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Discovered branch layout,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,424x304,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]
    runJs: executing `project.saveDiscoveredBranchLayout()`
    [intellij-stdout] closed Discovered branch layout
    runJs: executed `project.saveDiscoveredBranchLayout()`
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `8`
    callJs: evaluating `project.refreshGraphTableModel().getRowCount()`
    callJs: evaluated `project.refreshGraphTableModel().getRowCount()` to `0`
    runJs: executing `ide.closeOpenedProjects()`
    [intellij-stdout] project to close = Project(name=machete-sandbox-worktree, containerState=COMPONENT_CREATED, componentStore=/tmp/machete-tests-9998989093776029449/machete-sandbox-worktree)
    runJs: executed `ide.closeOpenedProjects()`

....

com.virtuslab.gitmachete.uitest.UITestSuite > discoverBranchLayout FAILED
    com.intellij.remoterobot.client.IdeaSideException: Wrapped java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
        at com.intellij.remoterobot.client.IdeRobotClient.throwIdeaSideError(IdeRobotClient.kt:142)
        at com.intellij.remoterobot.client.IdeRobotClient.processExecuteResponse(IdeRobotClient.kt:109)
        at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:59)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:35)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.com$virtuslab$gitmachete$uitest$RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$$runJs(RunningIntelliJFixtureExtension.scala:47)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$project$toolbar$.$anonfun$discoverBranchLayout$1(RunningIntelliJFixtureExtension.scala:243)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps.doAndAwait(RunningIntelliJFixtureExtension.scala:38)
        at com.virtuslab.gitmachete.uitest.RunningIntelliJFixtureExtension$RunningIntelliJFixtureOps$project$toolbar$.discoverBranchLayout(RunningIntelliJFixtureExtension.scala:243)
        at com.virtuslab.gitmachete.uitest.UITestSuite.discoverBranchLayout(UITestSuite.scala:123)

        Caused by:
        java.lang.Throwable: Wrapped java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
            at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1825)
            at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:227)
            at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
            at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:46)
            at org.mozilla.javascript.gen.js_1._c_anonymous_8(js:83)
            at org.mozilla.javascript.gen.js_1.call(js)
            at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:59)
            at org.mozilla.javascript.gen.js_1._c_anonymous_70(js:391)
            at org.mozilla.javascript.gen.js_1.call(js)
            at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:59)
            at org.mozilla.javascript.gen.js_1._c_anonymous_56(js:299)
            at org.mozilla.javascript.gen.js_1.call(js)
            at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:73)
            at org.mozilla.javascript.gen.js_7._c_script_0(js:11)
            at org.mozilla.javascript.gen.js_7.call(js)
            at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
            at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
            at org.mozilla.javascript.gen.js_7.call(js)
            at org.mozilla.javascript.gen.js_7.exec(js)
            at com.intellij.remoterobot.services.js.RhinoJavaScriptExecutor.executeWithContext(RhinoJavaScriptExecutor.kt:44)
            at com.intellij.remoterobot.services.js.RhinoJavaScriptExecutor.execute(RhinoJavaScriptExecutor.kt:23)
            at com.intellij.remoterobot.services.IdeRobot$doAction$3.invoke(IdeRobot.kt:305)
            at com.intellij.remoterobot.services.IdeRobot$doAction$3.invoke(IdeRobot.kt:297)
            at com.intellij.remoterobot.services.IdeRobot.getResult(IdeRobot.kt:389)
            at com.intellij.remoterobot.services.IdeRobot.doAction(IdeRobot.kt:297)
            at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$23$1.invoke(RobotServerImpl.kt:276)
            at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$23$1.invoke(RobotServerImpl.kt:274)
            at com.intellij.remoterobot.RobotServerImpl$Companion.commonRequest(RobotServerImpl.kt:354)
            at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$23.invokeSuspend(RobotServerImpl.kt:274)
            at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$23.invoke(RobotServerImpl.kt)
            at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$23.invoke(RobotServerImpl.kt)
            at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
            at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
            at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
            at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
            at io.ktor.routing.Routing.executeResult(Routing.kt:148)
            at io.ktor.routing.Routing.interceptor(Routing.kt:35)
            at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:100)
            at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
            at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
            at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
            at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:113)
            at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
            at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
            at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
            at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
            at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
            at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:121)
            at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
            at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
            at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
            at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
            at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
            at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:54)
            at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
            at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
            at kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:182)
            at kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source)
            at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:145)
            at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
            at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
            at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
            at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
            at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:829)

            Caused by:
            java.lang.Throwable: component must be showing on the screen to determine its location
                at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2117)
                at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2091)
                at org.assertj.swing.awt.AWT.locationOnScreenOf(AWT.java:316)
                at org.assertj.swing.awt.AWT.translate(AWT.java:101)
                at org.assertj.swing.core.RobotEventGenerator.lambda$pressMouse$0(RobotEventGenerator.java:75)
                at org.assertj.swing.edt.GuiActionRunner$1.executeInEDT(GuiActionRunner.java:75)
                at org.assertj.swing.edt.GuiQuery.run(GuiQuery.java:42)
                at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
                at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
                at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
                at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
                at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:98)
                at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:72)
                at org.assertj.swing.core.RobotEventGenerator.pressMouse(RobotEventGenerator.java:75)
                at org.assertj.swing.core.BasicRobot.doClickWhileModifiersPressed(BasicRobot.java:479)
                at org.assertj.swing.core.BasicRobot.lambda$doClick$1(BasicRobot.java:461)
                at org.assertj.swing.core.BasicRobot.pressModifiersWhileRunning(BasicRobot.java:504)
                at org.assertj.swing.core.BasicRobot.doClick(BasicRobot.java:461)
                at org.assertj.swing.core.BasicRobot.click(BasicRobot.java:453)
                at org.assertj.swing.core.BasicRobot.click(BasicRobot.java:430)
                at org.assertj.swing.core.BasicRobot.click(BasicRobot.java:414)
                at com.intellij.remoterobot.robot.SmoothRobot.click(SmoothRobot.kt:68)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206)
                ... 71 more
```

**Comment by PawelLipski** [comment]
Aaand again e.g. here https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/5677/workflows/de1f8c52-a1b8-40d5-9ab8-f0d233e857f9/jobs/5994

**Comment by PawelLipski** [comment]
Might've been fixed by #1056 🤞🏻

**Comment by mkondratek** [comment]
yup, we have not seen this one for a while

**Comment by PawelLipski** [comment]
Still occurring after #1056, see https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/6063/workflows/fc68a0c9-e9ae-430c-abe5-6e0dec5c5f30/jobs/6402... albeit seems less frequent

**Comment by PawelLipski** [comment]
Doesn't seem to happen anymore since v3.0.0; might've be limited to pre-2022 versions. Closing!
